/* Generated by tools/release.mjs. Do not edit. */
window.RABuild={"schemaVersion":1,"releaseId":"ra-e4748abd0a13-20261009142013","commit":"e4748abd0a13c10beb32fea99c8bc51691ea73fe","shortCommit":"e4748abd0a13","builtAt":"2026-10-09T14:20:13.354Z","assetVersion":"ra-e4748abd0a13-20261009142013"};
