/* Generated by tools/release.mjs. Do not edit. */
window.RABuild={"schemaVersion":1,"releaseId":"ra-3b8186ea96c8-20261009173221","commit":"3b8186ea96c80fd9ca5d85606d62a671d9cadeae","shortCommit":"3b8186ea96c8","builtAt":"2026-10-09T17:32:21.791Z","assetVersion":"ra-3b8186ea96c8-20261009173221"};
