/* Generated by tools/release.mjs. Do not edit. */
window.RABuild={"schemaVersion":1,"releaseId":"ra-679574164a67-20261009195218","commit":"679574164a6748f5fa402802e3fb9dd7f7e30416","shortCommit":"679574164a67","builtAt":"2026-10-09T19:52:18.393Z","assetVersion":"ra-679574164a67-20261009195218"};
