(function(){
  const checks=[
    ['core battle nodes',()=>['#startButton','#battleUI','#moves','#soundtrack'].every(sel=>document.querySelector(sel))],
    ['all move buttons',()=>document.querySelectorAll('[data-move]').length===4],
    ['conversion scene',()=>!!document.querySelector('#revealOverlay')],
    ['authored portrait room',()=>getComputedStyle(document.querySelector('.room')).backgroundImage.includes('throne_room_scene_portrait')],
    ['bedroom scene layers',()=>!!document.querySelector('#bedroomScene .bedroom-base')&&!!document.querySelector('#bedroomCloudCanvas')&&!!document.querySelector('#bedroomRich')],
    ['phone access and exact authored apps',()=>!!document.querySelector('#checkPhone')&&!!document.querySelector('#phoneOverlay')&&JSON.stringify(window.RAPhone?.apps)===JSON.stringify(['VampGPT','VampGram','InstaHoe','RealMoneyRealEstate','JDMIMPORTS','RICHBOIMPORTS','ONLYVAMPS'])],
    ['life state defaults',()=>RAState.get().version===6&&RAState.get().life.resources.money===100000&&RAState.get().life.world.location==='LA'&&RAState.get().life.resources.clout==='LOW'&&RAState.get().life.resources.vampireReputation==='LOW'&&typeof RAState.get().life.phone.learned==='boolean'&&RAState.get().life.acquisitions.active===null&&!('rich'in RAState.get())&&!('activeTrip'in RAState.get())],
    ['safe v4 save migration',()=>{const old={version:4,rich:{budget:42000,location:'Powder Springs, Georgia',clout:'LOW'},world:{day:3,month:2,scene:'stargazing'},phone:{learned:true},activeTrip:{id:'desire_trip_001',status:'arrived',destination:{name:'Powder Springs',region:'Georgia'},purpose:'butter chicken'},characters:{keep:{met:true}},encounters:{keep:{completed:true}}};const migrated=RAState.migrateRecord(old);return migrated.life.resources.money===42000&&migrated.life.world.location==='Powder Springs, Georgia'&&migrated.life.world.day===3&&migrated.life.world.month===2&&migrated.life.world.scene==='stargazing'&&migrated.life.phone.learned&&migrated.life.desires.activeTrip.id==='desire_trip_001'&&migrated.characters.keep.met&&migrated.encounters.keep.completed}],
    ['desire trip scene and state foundation',()=>!!window.RADesireTrips&&['planned','traveling','arrived','completed'].every(x=>RADesireTrips.statuses.includes(x))&&!!document.querySelector('#tripTravel')&&!!document.querySelector('#powderSpringsCurb')&&!!document.querySelector('#stargazingScene')&&Object.prototype.hasOwnProperty.call(RAState.get().life.desires,'activeTrip')],
    ['data-driven opportunity access',()=>{const a=RAOpportunities.get('atlanta'),t=RAOpportunities.get('tokyo');return a?.available===true&&t?.available===false&&t.lockedMessage==="tokyo vampires don't fw you yet. get your clout up."}],
    ['generic opportunity prerequisites',()=>{const life=RAState.get().life,rule={id:'test',requirements:{location:'LA',money:{minimum:100001},clout:{equals:'LOW'},vampireReputation:{equals:'LOW'},contact:'c1',relationship:{contactId:'c1',status:'friend'},prerequisiteFlag:'ready'}};const locked=RAOpportunities.evaluate(rule,life);const ready=JSON.parse(JSON.stringify(life));ready.resources.money=100001;ready.people.contacts.push('c1');ready.people.relationships.push({contactId:'c1',status:'friend'});ready.world.flags.ready=true;return !locked.available&&locked.failures.length===4&&RAOpportunities.evaluate(rule,ready).available}],
    ['v5 life save upgrades with new domain defaults',()=>{const migrated=RAState.migrateRecord({version:5,life:{resources:{money:777},world:{location:'LA'},desires:{activeTrip:null,completed:[]},ownership:{cars:[]}}});return migrated.version===6&&migrated.life.resources.money===777&&migrated.life.acquisitions.active===null&&Array.isArray(migrated.life.acquisitions.completed)&&migrated.life.ownership.cars.length===0}],
    ['JDMImports app and acquisition foundation',()=>RAPhone.apps.includes('JDMIMPORTS')&&!!RAJDMImports&&RAJDMImports.priceForTesting>0&&!RAState.get().life.ownership.cars.some(c=>c.id===RAJDMImports.carId)&&RAOpportunities.get('jdm_home_delivery')?.available===false&&!!document.querySelector('#jdmDockScene')&&!!document.querySelector('#supraPayoffScene')],
    ['developer life state inspector',()=>!!document.querySelector('#devLifeInspector')&&!!document.querySelector('#devLifeReadout')&&['#devLifeMoney','#devLifeLocation','#devLifeClout','#devLifeVampireRep','#devTokyoPreview'].every(sel=>!!document.querySelector(sel))],
    ['trip presentation layers and DEV scale selector',()=>!!document.querySelector('#tripRich')&&document.querySelectorAll('.trip-environment').length===2&&!!document.querySelector('#tripReturn')&&JSON.stringify([...document.querySelector('#devTripScale').options].map(o=>o.value))===JSON.stringify(['1','1.5','1.75','2'])],
    ['approved Powder Springs and Rich assets load at authored sizes',async()=>{const specs=[['powder_springs_night_270x480.png',270,480],...['eating','chilling','stargazing'].map(n=>[`rich_curb_${n}.png`,80,96])];const loaded=await Promise.all(specs.map(([file,w,h])=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i.naturalWidth===w&&i.naturalHeight===h);i.onerror=()=>resolve(false);i.src=`assets/${file}`})));return loaded.every(Boolean)}],
    ['native bedroom cloud canvas',()=>{const c=document.querySelector('#bedroomCloudCanvas');return c?.width===270&&c?.height===480&&getComputedStyle(c).imageRendering==='pixelated'}],
    ['bedroom authored state controls',()=>document.querySelectorAll('[data-bedroom-state]').length===6],
    ['bedroom source assets load at authored sizes',async()=>{const specs=[['rich_bedroom_environment_270x480.png',270,480],...['lounge_idle','phone_scroll','small_idle','phone_reaction','sleeping','drowsy_wake'].map(n=>[`rich_bedroom_${n}.png`,128,64]),['bedroom_cloud_large.png',136,40],['bedroom_cloud_medium.png',88,44],['bedroom_cloud_small.png',52,24]];const loaded=await Promise.all(specs.map(([file,w,h])=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i.naturalWidth===w&&i.naturalHeight===h);i.onerror=()=>resolve(false);i.src=`assets/${file}`})));return loaded.every(Boolean)}],
    ['state foundation',()=>!!window.RAState&&!!window.RACharacterSystem]
  ];
  async function run(){
    const results=[];for(const [name,test] of checks){let pass=false;try{pass=!!(await test());}catch(e){}results.push(`${pass?'PASS':'FAIL'} — ${name}`);}
    const summary=results.join('\n');console.log('[RA smoke]\n'+summary);const toast=document.querySelector('#toast');if(toast){toast.textContent=summary;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}return results;
  }
  window.RASmoke={run,checks};
})();
