import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {loadPlaywright,root} from '../tests/f05/_browser-lib.mjs';
const arg=n=>process.argv.includes(n)?process.argv[process.argv.indexOf(n)+1]:null,base=arg('--base'),phase=base?'before':'after',out=path.join(root,'docs/evidence/final_a/stage3');fs.mkdirSync(out,{recursive:true});
const cache=new Map(),mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.mp3':'audio/mpeg','.webp':'image/webp'};
if(base){const files=execFileSync('git',['-c','gc.auto=0','ls-tree','-r','--name-only',base],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(p=>['index.html','style.css','game.js'].includes(p)||p.startsWith('js/'));const bytes=execFileSync('git',['-c','gc.auto=0','cat-file','--batch'],{cwd:root,input:files.map(p=>`${base}:${p}\n`).join(''),maxBuffer:40*1024*1024});let offset=0;for(const p of files){const end=bytes.indexOf(10,offset),size=Number(bytes.subarray(offset,end).toString().split(' ').at(-1));cache.set(p,bytes.subarray(end+1,end+1+size));offset=end+size+2;}}
const server=http.createServer((req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\//,'')||'index.html';if(rel.includes('..'))throw Error('path');const bytes=cache.get(rel)||fs.readFileSync(path.join(root,rel));res.writeHead(200,{'content-type':mime[path.extname(rel)]||'application/octet-stream','cache-control':'no-store'});res.end(bytes);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const {chromium}=loadPlaywright(),browser=await chromium.launch({headless:true,executablePath:process.env.RA_CHROMIUM_PATH}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(`http://127.0.0.1:${server.address().port}/?dev=1&ff=F02.iron_and_grace,F02.armory`,{timeout:120000});await page.waitForFunction(()=>window.RAIronAndGrace);
 await page.evaluate(()=>{const s=RAState.migrateRecord(RASaveFixtures.fixtures.supraOwned);s.life.clock.started=true;for(const k of ['prologueDone','throneDone','firstWakeDone','armoryKnown'])s.life.world.flags[k]=true;s.life.combat.equippedMoves=['blood','octopus','bite','revenge'];RAState.write(localStorage,s,false);});await page.reload();await page.waitForFunction(()=>window.RAIronAndGrace);await page.evaluate(()=>{RAClock.wake({first:true});document.querySelector('#startButton')?.click();});await page.waitForFunction(()=>document.body.classList.contains('bedroom-mode'));
 await page.evaluate(async()=>{document.querySelector('.mail-done')?.click();document.querySelector('#devPanel')?.remove();RAIronAndGrace.grant('mac_and_cheese',{free:true});RAIronAndGrace.equip('mac_and_cheese');RAAudio.unlock();await RAAudio.preloadScene(['GN_01','MOVE_BLOODBATH','MOVE_BITE','MOVE_REVENGE','MOVE_OCTOPUS','HIT_LIGHT','HIT_HEAVY','KO','TELEGRAPH']);await document.fonts.ready;});
 // Warm exact accepted sprite bytes before the measured fight; this models the cached real encounter.
 await page.evaluate(async()=>{const srcs=[RACombatData.enemyArt('bonesworth').base,...Object.values(RACombatData.enemyArt('bonesworth').roles).map(r=>r.src),...Object.values(RAArtRegistry.combatMoves).flatMap(a=>Object.values(a).flat()).filter(s=>typeof s==='string'&&s.endsWith('.png'))];await Promise.all(srcs.map(src=>new Promise(resolve=>{const i=new Image();i.onload=i.onerror=resolve;i.src=src;})));});
 await page.evaluate(()=>{
  window.__frameAudit={frames:[],actions:[],phases:[],stops:[],first:null,last:null,running:true};const A=__frameAudit;let last=null,stop=null,action=null;
  const raf=t=>{if(!A.running)return;if(A.first===null)A.first=t;if(last!==null)A.frames.push({from:last,to:t,ms:t-last,action:action?.id||null});last=t;A.last=t;requestAnimationFrame(raf);};requestAnimationFrame(raf);
  document.addEventListener('pointerdown',e=>{const b=e.target.closest('.c2-scene [data-c2],.c2-scene [data-octo]');if(!b)return;const id=b.dataset.c2||`octopus:${b.dataset.octo}`;if(['fight','back','item','hoes'].includes(id))return;action={id,start:performance.now(),impacts:[],effects:[],settle:null};A.actions.push(action);A.phases.push({phase:'START',id,at:action.start});},true);
  const observer=new MutationObserver(ms=>{const root=document.querySelector('.c2-scene');if(!root)return;const t=performance.now(),paused=root.classList.contains('c2-impact-stop');if(paused&&stop===null){stop=t;A.phases.push({phase:'HIT-STOP START',id:action?.id,at:t});}if(!paused&&stop!==null){A.stops.push({start:stop,end:t,duration:t-stop});A.phases.push({phase:'HIT-STOP END',id:action?.id,at:t});stop=null;}
   for(const m of ms){if(m.target.matches?.('.c2-log')&&m.type==='childList'&&action){action.effects.push({at:t,text:m.target.textContent});A.phases.push({phase:'AUTHORED EFFECT',id:action.id,at:t,text:m.target.textContent});}if(m.type==='attributes'&&m.target.matches?.('.c2-pixel-fx')&&Number(m.target.dataset.frame)===3){action?.impacts.push(t);A.phases.push({phase:'PRESENTATION IMPACT',id:action?.id,at:t});}for(const n of m.addedNodes||[]){if(n.nodeType!==1)continue;if(n.matches?.('.c2-pixel-fx[data-presentation="contact"]')){action?.impacts.push(t);A.phases.push({phase:'IMPACT',id:action?.id,at:t});}}}
   if(action&&!action.settle&&root.querySelector('.c2-menu button,.c2-octo:not([hidden]) button')&&!RACombat2.active()?.busy()){action.settle=t;A.phases.push({phase:'SETTLE',id:action.id,at:t});}
  });observer.observe(document.querySelector('#screen'),{subtree:true,childList:true,attributes:true,attributeFilter:['class','data-frame']});
  window.__frameFight=RACombat2.run('bonesworth',{noPenalty:true});RACombat2.active().state.rng=()=>.4;
 });
 await page.waitForSelector('.c2-scene');let actions=0;
 for(let turn=0;turn<20;turn++){
  const state=await page.evaluate(()=>({over:RACombat2.active().state.over,revenge:RACombat2.active().state.rich.revenge,hp:RACombat2.active().state.rich.hp,ammo:RACombat2.active().state.__iagAmmo?.mac_and_cheese??2,pp:RACombat2.active().state.rich.pp}));if(state.over)break;
  if(turn===0){await page.click('[data-c2="fight"]');await page.click('[data-c2="move:octopus"]');await page.waitForSelector('.c2-octo [data-octo="roast"]');await page.click('.c2-octo [data-octo="roast"]');actions+=2;}
  else if(turn===1){await page.click('[data-c2="weapon:iron_and_grace_gun"]');actions++;}
  else{await page.click('[data-c2="fight"]');const id=state.revenge>=30&&state.pp.revenge?'revenge':state.hp<80&&state.pp.bite?'bite':state.pp.blood?'blood':'bite';await page.click(`[data-c2="move:${id}"]`);actions++;}
  await page.waitForFunction(()=>!RACombat2.active()?.busy(),null,{timeout:30000});
 }
 await page.waitForSelector('[data-c2="done"]',{timeout:30000});await page.evaluate(()=>{__frameAudit.running=false;const s=RACombat2.active().state;__frameAudit.outcome=s.outcome;__frameAudit.turns=s.turn;__frameAudit.final={rich:s.rich.hp,enemy:s.enemy.hp};});
 const data=await page.evaluate(()=>__frameAudit);data.actions=data.actions.filter(a=>a.id!=='done');const outside=data.frames.filter(f=>f.ms>50&&!data.stops.some(s=>f.from<=s.end&&f.to>=s.start)),inside=data.frames.filter(f=>f.ms>50&&data.stops.some(s=>f.from<=s.end&&f.to>=s.start));
 const sorted=data.frames.map(f=>f.ms).sort((a,b)=>a-b),summary={phase,base,width:390,outcome:data.outcome,turns:data.turns,actions:data.actions.length,actionsWithStart:data.actions.filter(a=>a.start!==null).length,actionsWithImpact:data.actions.filter(a=>a.impacts.length).length,actionsWithImpactOrEffect:data.actions.filter(a=>a.impacts.length||a.effects.length).length,actionsSettled:data.actions.filter(a=>a.settle!==null).length,frames:sorted.length,p95:sorted[Math.floor(sorted.length*.95)],max:sorted.at(-1),hitchesOutsideStops:outside.length,maxOutsideStops:Math.max(...data.frames.filter(f=>!data.stops.some(s=>f.from<=s.end&&f.to>=s.start)).map(f=>f.ms)),hitchesDuringStops:inside.length,intentionalStops:data.stops.length,errors};
 fs.writeFileSync(path.join(out,`frame-trace-${phase}.json`),JSON.stringify({summary,outside,inside,...data},null,2)+'\n');await page.locator('#screen').screenshot({path:path.join(out,`frame-trace-${phase}-end.png`)});console.log(JSON.stringify(summary));if(errors.length||!data.outcome||(!base&&outside.length))process.exitCode=1;
}finally{await browser.close();server.close();}
