import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),{chromium}=require(process.env.RA_PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(''),arg=n=>process.argv.includes(n)?process.argv[process.argv.indexOf(n)+1]:null,phase=arg('--phase')||'after',base=arg('--base'),out=path.join(root,'docs/evidence/final_a/stage1',phase);
fs.mkdirSync(out,{recursive:true});const cache=new Map(),types={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.mp3':'audio/mpeg','.ttf':'font/ttf'};
const server=http.createServer((req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://x').pathname).replace(/^\//,'')||'index.html';if(rel.includes('..'))throw Error();let b;if(base&&/\.(css|mjs|js|html|json)$/.test(rel)){if(!cache.has(rel))cache.set(rel,execFileSync('git',['-c','gc.auto=0','show',`${base}:${rel}`],{cwd:root,maxBuffer:30*1024*1024,stdio:['ignore','pipe','ignore']}));b=cache.get(rel);}else b=fs.readFileSync(path.join(root,rel));res.writeHead(200,{'content-type':types[path.extname(rel)]||'application/octet-stream'}).end(b);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.RA_CHROMIUM_PATH}),rows=[];
try{for(const width of [360,390,430]){
 const page=await browser.newPage({viewport:{width,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{let seed=7301;Math.random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};window.__timeTrace=[];window.__animTrace=[];window.__barTrace=[];const old=setTimeout;window.setTimeout=function(fn,ms,...args){const stack=Error().stack||'';const site=stack.split('\n').find(s=>/feel-(core|scenes|ui)\.mjs/.test(s));if(site)__timeTrace.push({ms,site:site.replace(/http:\/\/[^/]+\//,'')});return old(fn,ms,...args);};const animate=Element.prototype.animate;Element.prototype.animate=function(kf,opts){if(this.closest('#stage'))__animTrace.push({target:this.id||this.className,duration:typeof opts==='number'?opts:opts.duration,iterations:opts.iterations||1});if(this.matches('.decide .bar i'))__barTrace.push({duration:opts.duration,keyframes:kf});return animate.call(this,kf,opts);};document.addEventListener('DOMContentLoaded',()=>{const seen=new WeakSet();new MutationObserver(()=>{const d=document.querySelector('.decide');if(!d||seen.has(d))return;const b=d.querySelector('button[data-id="OUT"]')||d.querySelector('button');if(!b)return;seen.add(d);old(()=>b.click(),30);}).observe(document.body,{childList:true,subtree:true});});});
 await page.goto(`http://127.0.0.1:${server.address().port}/assets/f01/play/index.html?seed=7&fresh=1&speed=10`,{waitUntil:'domcontentloaded',timeout:120000});
 await page.click('.title');await page.waitForSelector('.b-ans');await page.click('.b-ans');await page.waitForSelector('.send');await page.waitForTimeout(350);await page.click('.send');await page.waitForSelector('.phone',{timeout:60000});
 await page.evaluate(()=>document.fonts.ready);await page.waitForSelector('.bub:not(.typing)');
 const geometry=await page.evaluate(()=>{const props=['left','right','top','bottom','width','height','padding','borderWidth','fontFamily','fontSize','lineHeight','letterSpacing','animationDuration','transitionDuration'];return Object.fromEntries(['.phone','.ph-head','.msgs','.bub:not(.typing)','.decide','.decide button','.decide .bar','.decide .bar i'].map(sel=>{let e=document.querySelector(sel),temp=false;if(!e){e=document.createElement('div');e.className=sel.split('.').at(-1).split(' ')[0];const parent=document.querySelector('.phone');parent.append(e);temp=true;}const c=getComputedStyle(e),v=Object.fromEntries(props.map(p=>[p,c[p]]));if(temp)e.remove();return [sel,v];}));});
 await page.screenshot({path:path.join(out,`${width}-play-chat.png`)});
 const started=Date.now();while(Date.now()-started<120000){if(await page.locator('.again').count())break;await page.waitForTimeout(100);}
 if(!await page.locator('.again').count())throw Error('PLAY trace did not terminate');
 rows.push({width,errors,geometry,...await page.evaluate(()=>({timers:__timeTrace,animations:__animTrace,bars:__barTrace,rec:__raPlay.G.last.rec,audio:__raFeelAudio}))});await page.close();
 }
 fs.writeFileSync(path.join(out,'feel-trace.json'),JSON.stringify({phase,base,rows},null,2)+'\n');
 if(phase==='after'){
 const before=JSON.parse(fs.readFileSync(path.join(root,'docs/evidence/final_a/stage1/before/feel-trace.json'),'utf8'));const unique=x=>[...new Set(x.map(v=>JSON.stringify(v)))].sort();const comparisons=rows.map((r,i)=>({width:r.width,timerDurations:JSON.stringify(unique(r.timers))===JSON.stringify(unique(before.rows[i].timers)),animationDurations:JSON.stringify(unique(r.animations))===JSON.stringify(unique(before.rows[i].animations)),callBars:JSON.stringify(r.bars)===JSON.stringify(before.rows[i].bars),geometry:JSON.stringify(r.geometry)===JSON.stringify(before.rows[i].geometry),outcome:JSON.stringify(r.rec)===JSON.stringify(before.rows[i].rec),errors:r.errors,rawCounts:{timers:[before.rows[i].timers.length,r.timers.length],animations:[before.rows[i].animations.length,r.animations.length],audio:[before.rows[i].audio.length,r.audio.length]}}));
 fs.writeFileSync(path.join(root,'docs/evidence/final_a/stage1/feel-comparison.json'),JSON.stringify({method:'Compare scheduled intervals and animation durations, call bar clocks, geometry and gameplay record. Ambient heartbeat tick counts vary with wall-clock browser scheduling and are retained, not treated as an engine change.',comparisons},null,2)+'\n');console.log(JSON.stringify(comparisons));if(comparisons.some(r=>!r.timerDurations||!r.animationDurations||!r.callBars||!r.geometry||!r.outcome||r.errors.length))process.exitCode=1;
 }else console.log(`before PLAY timing traces: ${rows.length}`);
}finally{await browser.close();server.close();}
