// BUILD-4 supplemental registry: preserve the generated Ship 004–015 registry and add approved inputs.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {buildRegistry} from '../art-registry.mjs';
import {decodePng} from '../presentation/png.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const json=async p=>JSON.parse(await readFile(path.join(root,p),'utf8'));
export async function supplemental(){
 const base=await buildRegistry(),out={assets:{},environments:{},characters:{}};
 async function add(p,status,expected,authority){
  if(base.assets[p]||out.assets[p])return;
  const b=await readFile(path.join(root,p)),sha=createHash('sha256').update(b).digest('hex');
  if(expected&&sha!==expected)throw new Error(`BUILD4 approval hash mismatch: ${p}`);
  const png=decodePng(b);out.assets[p]={sha256:sha,width:png.width,height:png.height,status,authority};
 }
 for(const a of (await json('art_department/ASSET_REGISTER.json')).assets.filter(a=>a.status==='FROZEN'))
  await add(a.path,'FROZEN',a.sha256,'art_department/ASSET_REGISTER.json');
 const f15='art_department/production/f15-date-scene-assets';
 const pkg=await json(`${f15}/manifest.json`);
 for(const a of [...pkg.approved_production,...pkg.approved_originals])await add(`${f15}/${a.path}`,'FROZEN',a.sha256,`${f15}/manifest.json`);
 const audit=await json('art_department/build4/PRESERVED_ART_HASH_AUDIT.json');
 for(const [p,a] of Object.entries(audit.branches['art/f15-launch-trio-masters'].files))
  if(p.endsWith('.png'))await add(p,'FROZEN',a.sha256,'preserve/art-f15-launch-trio-masters');
 for(const [p,a] of Object.entries(audit.branches['art/f07-warehouse-backgrounds'].files))
  await add(p,'FROZEN',a.sha256,'preserve/art-f07-warehouse-backgrounds');
 // OL-012 approves corrected Gbenga v2 and Carlos v1, including the exact native runtime states.
 const rows=(await json('art_department/ASSET_REGISTER.json')).assets;
 for(const id of ['gbenga','carlos']){
  const states={};
  for(const a of rows.filter(a=>a.status==='FROZEN'&&a.path.includes(`/characters/${id}/runtime_80x96/`)))
   states[a.state.toLowerCase().replace(/[^a-z0-9]+/g,'_')]=a.path;
  const neutral=states.neutral||states.neutral_happy;
  // Gbenga's neutral includes his desk; the approved standing sleeves pose is the stage default.
  const pose=id==='gbenga'?'adjusting_sleeves':'neutral';
  if(neutral&&!base.characters[id])out.characters[id]={anchor:states[pose]||neutral,anchorPose:pose,cell:[80,96],contact:[40,88],states:{...states,neutral}};
 }
 const scene=await json('assets/f15/scene_art_manifest.json');
 for(const a of scene.files)await add(a.path,a.approved_sha256?'FROZEN':'CREATOR_REVIEW',a.sha256,'assets/f15/scene_art_manifest.json');
 const f07='assets/f07/backgrounds/warehouse_owambe_party_270x480.png';
 await add(f07,'FROZEN',audit.branches['art/f07-warehouse-backgrounds'].files['art_department/production/f07-warehouse-backgrounds/interiors/warehouse_owambe_party_270x480.png'].sha256,'preserve/art-f07-warehouse-backgrounds');
 const ext='assets/f07/backgrounds/warehouse_exterior_270x480.png';
 await add(ext,'FROZEN',audit.branches['art/f07-warehouse-backgrounds'].files['art_department/production/f07-warehouse-backgrounds/exteriors/warehouse_exterior_270x480.png'].sha256,'preserve/art-f07-warehouse-backgrounds');
 out.environments.f07_warehouse_party={asset:f07};out.environments.f07_warehouse_exterior={asset:ext};
 const ids={f15_bing:'the_bing',f15_gym:'boxing_gym',f15_roxy_apartment:'roxy_apartment',f15_plenitude:'plenitude',f15_convention:'convention_hall',f15_rosalyn_apartment:'rosalyn_apartment',f15_shrine:'shrine_auditorium'};
 for(const [id,name] of Object.entries(ids))out.environments[id]={asset:`assets/f15/environments/${name}_270x480.png`};
 out.environments.f15_rosalyn_apartment_dark={asset:out.environments.f15_rosalyn_apartment.asset,layers:{lights_off:'assets/f15/layers/lights_off_270x480.png'},status:'FROZEN',authority:'OL-042 A1'};
 const granny=scene.files.find(a=>a.path.includes('granny_bing_neutral')).path;
 if(!base.characters.granny_bing)out.characters.granny_bing={anchor:granny,cell:[80,96],contact:[40,88],states:{neutral:granny}};
 const roach=scene.files.find(a=>a.path.includes('spirit_of_uncle_bunmi_444')).path;
 if(!base.characters.spirit_of_uncle_bunmi)out.characters.spirit_of_uncle_bunmi={anchor:roach,cell:[444,222],contact:[220,222],states:{neutral:roach},status:'FROZEN',authority:'OL-042 A2'};
 return out;
}
export async function expectedPart(){return `// Generated by tools/build4/registry.mjs; additive only. F12 owns preserved art. Review status never implies Ube approval.\nRAArtParts.register('F12',${JSON.stringify(await supplemental(),null,1)});\n`;}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const part=await expectedPart(),target=path.join(root,'js/data/art/parts/F12_preserved.js');
 if(process.argv.includes('--check')){if((await readFile(target,'utf8')).replace(/\r\n/g,'\n')!==part)throw new Error('BUILD4 registry part is stale');console.log('PASS BUILD4 supplemental art registry hashes and generated metadata');}
 else{await writeFile(target,part);console.log('BUILD4 supplemental registry written');}
}
