import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require('playwright-core');
const origin=process.argv[2],out=process.argv[3];assert(origin&&out,'origin/output required');await fs.mkdir(out,{recursive:true});
const checks=[],captures=[],errors=[],dialogs=[],failures=[];let current='source';
const check=(name,value,details)=>{assert(value,name+' '+JSON.stringify(details||''));checks.push({name,pass:true,...(details?{details}:{})});};
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
const browser=await chromium.launch({channel:'chrome',headless:true});
async function page(c){const p=await c.newPage();p.on('pageerror',e=>errors.push({current,error:e.message}));p.on('dialog',async d=>{dialogs.push({current,message:d.message()});await d.dismiss();});p.on('requestfailed',r=>{if(!/ERR_ABORTED/.test(r.failure()?.errorText||''))failures.push({current,url:r.url(),error:r.failure()?.errorText});});return p;}
async function ready(p){await p.waitForFunction(()=>window.RAAstraCheckoutPlaceholder&&window.RAEntryFlow&&window.RAOpeningCinema?.ready);}
async function game(p){await p.waitForFunction(()=>RAEntryFlow.mode==='game'&&!RAOpeningCinema.isVisible());}
async function state(p){return p.evaluate(()=>({active:RAAdventures.active(),money:RAState.get().life.resources.money,followers:RAState.get().life.resources.followers,ownership:RAState.get().life.ownership}));}
async function shot(p,name){await p.screenshot({path:path.join(out,name)});captures.push({name,current});}
const report={origin,scope:'Own disposable Chromium contexts. Earlier-frame/end-card seek probes are labelled renderer fixtures. Skip/Continue and the natural forty-second ending use native inputs; the recording is unretimed. No user profile, source replacement or forced outcome.'};
try{
 const [js,html]=await Promise.all(['js/systems/opening_cinema.js','index.html'].map(x=>fetch(new URL(x,origin)).then(r=>{assert(r.ok);return r.text();})));
 check('No displayed sample labels in cinematic runtime/fallback',!js.includes('SAMPLE')&&!html.includes('OPENING SAMPLE')&&!html.includes('cinema-poster" src="opening-assets/first-frame.png'));
 check('Existing forty-second timeline and unchanged skip wording',js.includes('const DURATION=40;')&&html.includes('>Click here to skip</button>'));
 for(const [w,h]of[[360,800],[390,844],[430,932],[1280,900]]){
  current='card renderer fixture '+w;const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:w<500,isMobile:w<500}),p=await page(c);await p.goto(origin);await ready(p);await p.locator('#startButton').click();await p.evaluate(()=>{
   window.__endingPaint=[];const fill=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(s,x,y,...a){if(s==='Rich Alucard')__endingPaint.push({text:s,font:this.font,color:this.fillStyle,alpha:this.globalAlpha,x,y});return fill.call(this,s,x,y,...a);};
  });
  if(w===390&&process.env.RA_INTRO_FRAME_REFERENCES){const refs=JSON.parse(await fs.readFile(process.env.RA_INTRO_FRAME_REFERENCES,'utf8'));for(const ref of refs){await p.evaluate(t=>RAOpeningCinema.seek(t),ref.time??ref.t);const actual=sha(Buffer.from(await p.evaluate(()=>film.toDataURL('image/png').split(',')[1]),'base64'));check('Unchanged approved roadside frame '+(ref.time??ref.t),actual===(ref.sha256??ref.hash));}}
  await p.evaluate(()=>RAOpeningCinema.seek(38.5));const full=await p.evaluate(()=>{const d=film.getContext('2d').getImageData(0,0,640,360).data;let energy=0,red=0,other=0,outsideTitle=0;const m=document.createElement("canvas").getContext("2d");m.font=__endingPaint.at(-1).font;const width=m.measureText("Rich Alucard").width;for(let i=0;i<d.length;i+=4){energy+=d[i]+d[i+1]+d[i+2];if(d[i]||d[i+1]||d[i+2]){if(d[i]>d[i+1]&&d[i]>d[i+2])red++;else other++;const x=(i/4)%640,y=Math.floor(i/4/640);if(x<320-width/2-3||x>320+width/2+3||y<155||y>205)outsideTitle++;}}return {energy,red,other,outsideTitle,paint:__endingPaint.at(-1),background:getComputedStyle(cinematicIntro).backgroundColor,font:getComputedStyle(document.documentElement).getPropertyValue('--font-system'),fontLoaded:document.fonts.check('28px "Press Start 2P"'),overflow:document.documentElement.scrollWidth>innerWidth};});
  check(current+' only red title on black',full.red>500&&full.outsideTitle===0&&full.paint.color==='#d7193f'&&full.background==='rgb(0, 0, 0)',full);
  check(current+' established game font and exact centered title',full.paint.text==='Rich Alucard'&&full.paint.font.includes('Press Start 2P')&&full.font.includes('Press Start 2P')&&full.fontLoaded&&full.paint.x===320&&full.paint.y===180&&!full.overflow,full.paint);
  await shot(p,'ending-card-'+w+'.png');await p.evaluate(()=>RAOpeningCinema.seek(39.8));const fade=await p.evaluate(()=>{const d=film.getContext('2d').getImageData(0,0,640,360).data;let sum=0;for(let i=0;i<d.length;i+=4)sum+=d[i]+d[i+1]+d[i+2];return sum;});check(current+' text fades toward black',fade>0&&fade<full.energy*.25,{full:full.energy,fade});await p.evaluate(()=>RAOpeningCinema.seek(40));check(current+' final frame is black',await p.evaluate(()=>{const d=film.getContext('2d').getImageData(0,0,640,360).data;for(let i=0;i<d.length;i+=4)if(d[i]||d[i+1]||d[i+2])return false;return true;}));await c.close();
 }
 for(const [w,h]of[[360,800],[390,844],[430,932],[1280,900]]){
  current='native skip/Continue '+w;const c=await browser.newContext({viewport:{width:w,height:h},hasTouch:w<500,isMobile:w<500}),p=await page(c);await p.goto(origin);await ready(p);await p.locator('#startButton').click();await p.waitForFunction(()=>RAOpeningCinema.isVisible());await p.locator('#cinemaSkipHint').click();await game(p);const before=await state(p);check(current+' skip enters fresh game',before.money===40000&&before.active?.node==='arrive');await p.reload();await ready(p);check(current+' reload shows Continue with no cinematic',await p.locator('#startButton').innerText()==='CONTINUE'&&await p.evaluate(()=>!RAOpeningCinema.isVisible()));await p.locator('#startButton').click();await game(p);check(current+' exact checkpoint/resources preserved',JSON.stringify(before)===JSON.stringify(await state(p)));await c.close();
 }
 current='natural unretimed ending';const record=process.env.RA_ENDING_RECORD==='1',c=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,...(record?{recordVideo:{dir:path.join(out,'video'),size:{width:390,height:844}}}:{})}),p=await page(c);await p.goto(origin);await ready(p);
 await p.evaluate(()=>{
  const fill=CanvasRenderingContext2D.prototype.fillText;window.__naturalEnding=null;window.__naturalFade=null;
  CanvasRenderingContext2D.prototype.fillText=function(s,x,y,...a){const result=fill.call(this,s,x,y,...a);if(s==='Rich Alucard'){const time=RAOpeningCinema.time;if(time>=38.5&&time<39.2&&!__naturalEnding)__naturalEnding={time,text:s,font:this.font,color:this.fillStyle,alpha:this.globalAlpha,png:this.canvas.toDataURL('image/png')};if(time>=39.8&&!__naturalFade)__naturalFade={time,alpha:this.globalAlpha};}return result;};
 });
 const clickMs=await p.evaluate(()=>performance.now()),began=Date.now();await p.locator('#startButton').tap();await p.waitForFunction(()=>window.__naturalEnding,null,{timeout:52000});const natural=await p.evaluate(()=>__naturalEnding);check('Natural title uses exact text/game font/red without seek',natural.text==='Rich Alucard'&&natural.font.includes('Press Start 2P')&&natural.color==='#d7193f'&&natural.alpha===1,{time:natural.time,font:natural.font,color:natural.color});await fs.writeFile(path.join(out,'natural-title-native.png'),Buffer.from(natural.png.split(',')[1],'base64'));await shot(p,'natural-title-viewport.png');await game(p);const elapsedMs=Date.now()-began;await p.waitForTimeout(1500);await shot(p,'natural-game-settled.png');
 const final=await p.evaluate(()=>({filmTime:RAOpeningCinema.time,filmHidden:!RAOpeningCinema.isVisible(),titleHidden:getComputedStyle(startOverlay).display==='none',active:RAAdventures.active(),money:RAState.get().life.resources.money,fade:__naturalFade,build:window.RABuild}));check('Natural forty-second ending fades then enters native game once',elapsedMs>=39000&&elapsedMs<55000&&final.filmTime===40&&final.filmHidden&&final.titleHidden&&final.active?.node==='arrive'&&final.money===40000&&final.fade.alpha<.16,{elapsedMs,...final});await p.waitForTimeout(1500);const endMs=await p.evaluate(()=>performance.now());if(record){const video=p.video();await c.close();report.recording={raw:await video.path(),clipStartSeconds:clickMs/1000+35.2,clipDurationSeconds:endMs/1000-(clickMs/1000+35.2),clickMs,endMs,elapsedMs,scope:'Last seconds of an actual complete forty-second native cinematic followed by its new-game scene. No seek, timing changes or forced outcome. Silent browser video.',build:final.build};}else await c.close();
 check('No browser dialogs',dialogs.length===0,dialogs);check('No page errors',errors.length===0,errors);check('No unexpected request failures',failures.length===0,failures);
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({...report,status:'PASS',checks,captures,errors,dialogs,failures},null,2)+'\n');console.log('PASS '+checks.length+' ending checks');
}catch(e){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({...report,status:'FAIL',current,error:e.stack,checks,captures,errors,dialogs,failures},null,2)+'\n');throw e;}finally{await browser.close();}
