import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import{createRequire}from'node:module';
const require=createRequire(import.meta.url),{chromium}=require('playwright-core'),origin=process.argv[2],out=process.argv[3];await fs.mkdir(out,{recursive:true});
const checks=[],captures=[],errors=[],dialogs=[],requestFailures=[];let current='boot';const browser=await chromium.launch({channel:'chrome',headless:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const check=(name,value,details)=>{assert(value,name+' '+JSON.stringify(details||''));checks.push({name,pass:true,...(details?{details}:{})});};
const old=process.env.RA_INTRO_OLD_SAVE?JSON.parse(await fs.readFile(process.env.RA_INTRO_OLD_SAVE,'utf8')):null;
async function context(width=390,height=844,extra={},seed=null){const c=await browser.newContext({viewport:{width,height},hasTouch:width<500,isMobile:width<500,...extra});if(seed)await c.addInitScript(data=>{if(window===window.top&&/^https?:$/.test(location.protocol)&&!sessionStorage.getItem('entry-seed')){localStorage.setItem('rich_alucard_save_v1',JSON.stringify(data));sessionStorage.setItem('entry-seed','1');}},seed);return c;}
async function page(c){const p=await c.newPage();p.on('pageerror',e=>errors.push({current,error:e.message}));p.on('dialog',async d=>{dialogs.push({current,type:d.type(),message:d.message()});await d.dismiss();});p.on('requestfailed',r=>{if(!/ERR_ABORTED/.test(r.failure()?.errorText||''))requestFailures.push({url:r.url(),error:r.failure()?.errorText});});return p;}
async function ready(p){await p.waitForFunction(()=>window.RAAstraCheckoutPlaceholder&&window.RAEntryFlow&&window.RAOpeningCinema?.ready);}
async function instrument(p){await p.evaluate(()=>{window.__entryCalls={start:0,reset:0};const a=RANewGame.onStart,r=RAState.reset;RANewGame.onStart=function(...args){__entryCalls.start++;return a.apply(this,args);};RAState.reset=function(...args){__entryCalls.reset++;return r.apply(this,args);};});}
async function resources(p){return p.evaluate(()=>{const l=RAState.get().life;return {money:l.resources.money,followers:l.resources.followers,ownership:l.ownership,clock:l.clock,active:l.adventures.active};});}
async function shot(p,name){await p.screenshot({path:path.join(out,name)});captures.push({file:name,case:current});}
async function game(p){await p.waitForFunction(()=>RAEntryFlow.mode==='game'&&!RAOpeningCinema.isVisible()&&getComputedStyle(startOverlay).display==='none');}
try{
 for(const [w,h]of[[320,720],[360,800],[390,844],[430,932],[1280,900],[1440,900],[844,390],[390,600]]){
  current='first-title '+w+'x'+h;const c=await context(w,h),p=await page(c);await p.goto(origin,{waitUntil:'domcontentloaded'});await ready(p);
  check(current+' no automatic cinematic',await p.evaluate(()=>!RAOpeningCinema.isVisible()&&!RAOpeningCinema.playing&&RAOpeningCinema.time===0&&!startOverlay.hidden));
  check(current+' fresh New Game action',await p.locator('#startButton').innerText()==='NEW GAME'&&await p.locator('#newGameButton').isHidden());
  const fit=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,stage:document.querySelector('#stage').inert}));check(current+' no horizontal overflow and stage inert',!fit.overflow&&fit.stage,fit);
  if(w===390&&h===844)await shot(p,'title-first-390.png');await c.close();
 }
 current='approved frames';const frameCtx=await context(),f=await page(frameCtx);await f.goto(origin);await ready(f);await instrument(f);await f.locator('#startButton').tap();await f.waitForFunction(()=>RAOpeningCinema.isVisible());
 if(process.env.RA_INTRO_FRAME_REFERENCES){const raw=JSON.parse(await fs.readFile(process.env.RA_INTRO_FRAME_REFERENCES,'utf8'));const refs=Array.isArray(raw)?raw:raw.frames;for(const ref of refs){const time=ref.time??ref.t;await f.evaluate(t=>RAOpeningCinema.seek(t),time);const data=await f.evaluate(()=>document.querySelector('#film').toDataURL('image/png').split(',')[1]);const actual=sha(Buffer.from(data,'base64'));check('approved cinematic frame '+time,actual===(ref.sha256??ref.hash),{actual,expected:ref.sha256??ref.hash});}}
 await f.locator('#cinemaSkipHint').tap();await game(f);check('frame fixture starts native game once',await f.evaluate(()=>__entryCalls.start===1&&__entryCalls.reset===0&&RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE'));await frameCtx.close();
 for(const [w,h]of[[360,800],[390,844],[430,932],[1280,900]]){
  current='fresh new-game '+w;const c=await context(w,h),p=await page(c);await p.goto(origin);await ready(p);await instrument(p);
  await p.locator('#startButton').click();await p.evaluate(()=>{document.querySelector('#startButton').click();document.querySelector('#newGameButton').click();});
  check(current+' cinema before native start',await p.evaluate(()=>RAEntryFlow.mode==='cinematic'&&RAOpeningCinema.isVisible()&&startOverlay.hidden&&__entryCalls.start===0&&__entryCalls.reset===0&&!RAAdventures.active()));
  const rect=await p.locator('#film').boundingBox(),hint=await p.locator('#cinemaSkipHint').boundingBox();check(current+' uncropped cinema and touch hint',rect.x>=0&&rect.y>=0&&rect.x+rect.width<=w+1&&rect.y+rect.height<=h+1&&hint.height>=44,{rect,hint});
  check(current+' approved hint only',await p.locator('#cinemaSkipHint').innerText()==='Click here to skip'&&await p.locator('#cinematicIntro button').count()===1);
  await p.keyboard.down('Space');await p.keyboard.down('Space');await game(p);const active=await p.evaluate(()=>JSON.stringify(RAAdventures.active()));await p.keyboard.up('Space');await p.waitForTimeout(100);
  check(current+' skip key does not advance game',active===await p.evaluate(()=>JSON.stringify(RAAdventures.active())));
  check(current+' once-only native launch and initial cash',await p.evaluate(()=>__entryCalls.start===1&&__entryCalls.reset===0&&RAState.get().life.resources.money===40000&&!document.querySelector('#stage').inert));
  if(w===390)await shot(p,'new-game-after-skip-390.png');await p.reload();await ready(p);check(current+' reload title Continue',await p.locator('#startButton').innerText()==='CONTINUE'&&await p.evaluate(()=>!RAOpeningCinema.isVisible()));await instrument(p);await p.locator('#startButton').click();await p.locator('#startButton').evaluate(e=>e.click());await game(p);
  check(current+' direct Continue resumes exact fresh checkpoint',active===await p.evaluate(()=>JSON.stringify(RAAdventures.active()))&&await p.evaluate(()=>__entryCalls.start===1&&__entryCalls.reset===0&&!RAOpeningCinema.playing));await c.close();
 }
 if(old)for(const [w,h]of[[360,800],[390,844],[430,932],[1280,900]]){
  current='existing-save '+w;const c=await context(w,h,{},old),p=await page(c);await p.goto(origin);await ready(p);await instrument(p);const before=await resources(p),all=await p.evaluate(()=>JSON.stringify(RAState.get()));
  await p.locator('#newGameButton').click();check(current+' inline overwrite choice',await p.locator('#startButton').innerText()==='REPLACE SAVE'&&await p.locator('#newGameButton').innerText()==='CANCEL'&&await p.locator('#entryNotice').isVisible());
  check(current+' arm changes no save',all===await p.evaluate(()=>JSON.stringify(RAState.get()))&&await p.evaluate(()=>!RAOpeningCinema.isVisible()));if(w===390)await shot(p,'overwrite-choice-390.png');
  await p.locator('#newGameButton').click();check(current+' cancel preserves full state',all===await p.evaluate(()=>JSON.stringify(RAState.get()))&&await p.locator('#startButton').innerText()==='CONTINUE');
  await p.locator('#startButton').focus();await p.keyboard.press('Enter');await game(p);const after=await resources(p);check(current+' native Continue preserves resources/ownership',JSON.stringify({money:before.money,followers:before.followers,ownership:before.ownership})===JSON.stringify({money:after.money,followers:after.followers,ownership:after.ownership}),{money:after.money,followers:after.followers});
  check(current+' direct Continue no cinema or reset',await p.evaluate(()=>__entryCalls.start===1&&__entryCalls.reset===0&&!RAOpeningCinema.isVisible()&&RAOpeningCinema.time===0));if(w===390)await shot(p,'continue-direct-390.png');
  await p.reload();await ready(p);await instrument(p);const preReplace=await resources(p);await p.locator('#newGameButton').click();await p.locator('#startButton').click();await p.waitForFunction(()=>RAOpeningCinema.isVisible());
  check(current+' old save kept during cinematic',JSON.stringify(preReplace)===JSON.stringify(await resources(p))&&await p.evaluate(()=>__entryCalls.reset===0&&__entryCalls.start===0));await p.locator('#cinemaSkipHint').click();await game(p);
  check(current+' confirmed native reset once',await p.evaluate(()=>__entryCalls.reset===1&&__entryCalls.start===1&&RAState.get().life.resources.money===40000&&RAState.get().life.resources.followers===0&&RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE'));await c.close();
 }
 current='held Enter activation';const keyCtx=await context(1280,900),k=await page(keyCtx);await k.goto(origin);await ready(k);await instrument(k);await k.locator('#startButton').focus();await k.keyboard.down('Enter');await k.keyboard.down('Enter');await k.waitForTimeout(150);
 check('held New Game Enter cannot skip its film',await k.evaluate(()=>RAOpeningCinema.isVisible()&&__entryCalls.start===0));await k.keyboard.up('Enter');await k.locator('#cinemaSkipHint').focus();await k.keyboard.down('Enter');await k.keyboard.down('Enter');await game(k);const keyActive=await k.evaluate(()=>JSON.stringify(RAAdventures.active()));await k.keyboard.up('Enter');await k.waitForTimeout(100);check('held hint Enter cannot advance fresh game',keyActive===await k.evaluate(()=>JSON.stringify(RAAdventures.active()))&&await k.evaluate(()=>__entryCalls.start===1));await keyCtx.close();
 current='reduced motion';const redCtx=await context(390,844,{reducedMotion:'reduce'}),r=await page(redCtx);await r.goto(origin);await ready(r);check('reduced title remains first and silent',await r.evaluate(()=>!RAOpeningCinema.isVisible()&&document.querySelector('#retroPlayPreview').paused));await r.locator('#startButton').tap();await r.waitForTimeout(300);check('reduced New Game static film with unchanged hint',await r.evaluate(()=>RAOpeningCinema.isVisible()&&!RAOpeningCinema.playing&&RAOpeningCinema.time===0)&&await r.locator('#cinemaSkipHint').innerText()==='Click here to skip');await r.emulateMedia({reducedMotion:'no-preference'});await r.waitForFunction(()=>RAOpeningCinema.playing&&RAOpeningCinema.time>0);check('dynamic motion resumes film',true);await r.locator('#cinemaSkipHint').tap();await game(r);await redCtx.close();
 if(old){
  current='reset save failure';const failCtx=await context(390,844,{},old),s=await page(failCtx);await s.goto(origin);await ready(s);await instrument(s);const saved=await s.evaluate(()=>JSON.stringify(RAState.get()));await s.locator('#newGameButton').click();await s.locator('#startButton').click();await s.evaluate(()=>{window.__entryOriginalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key===RAState.keys.primary)throw new DOMException('Controlled reset write denial','QuotaExceededError');return __entryOriginalSet.call(this,key,value);};});await s.locator('#cinemaSkipHint').tap();await s.waitForFunction(()=>RAEntryFlow.mode==='title');check('failed reset retains complete live save',saved===await s.evaluate(()=>JSON.stringify(RAState.get())));check('failed reset retains title and readable retry',await s.locator('#startButton').innerText()==='CONTINUE'&&await s.locator('#entryNotice').innerText()==='Your save could not be replaced. Please try again.');await s.evaluate(()=>{Storage.prototype.setItem=__entryOriginalSet;RAState.load();});check('failed reset retains durable save after load',saved===await s.evaluate(()=>JSON.stringify(RAState.get())));await s.locator('#startButton').tap();await game(s);check('saved game still continues after reset failure',await s.evaluate(()=>__entryCalls.start===1&&!RAOpeningCinema.isVisible()));await failCtx.close();
  current='blocked optional audio';const audioCtx=await context(390,844,{},old);await audioCtx.addInitScript(()=>{const play=HTMLMediaElement.prototype.play;window.__audioDenials=0;HTMLMediaElement.prototype.play=function(){if(this.tagName==='AUDIO'){__audioDenials++;return Promise.reject(new DOMException('Controlled startup audio denied','NotAllowedError'));}return play.call(this);};});const a=await page(audioCtx);await a.goto(origin);await ready(a);await a.locator('#startButton').tap();await game(a);await a.waitForTimeout(200);check('blocked optional audio adds no startup popup',await a.evaluate(()=>__audioDenials>0&&!document.querySelector('#toast')?.textContent.includes('TAP AGAIN FOR AUDIO')&&RAEntryFlow.mode==='game'));await audioCtx.close();
 }
 current='natural full New Game';const natural=await context(),n=await page(natural);await n.goto(origin);await ready(n);await instrument(n);await n.locator('#startButton').tap();const began=Date.now();await n.waitForFunction(()=>RAEntryFlow.mode==='game',null,{timeout:52000});check('natural forty-second film enters game without returning to title',await n.evaluate(()=>RAOpeningCinema.time===40&&!RAOpeningCinema.isVisible()&&getComputedStyle(startOverlay).display==='none'&&__entryCalls.start===1&&__entryCalls.reset===0&&RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE'),{elapsedMs:Date.now()-began});await shot(n,'natural-game-390.png');await natural.close();
 check('no browser confirmation or other dialogs',dialogs.length===0,dialogs);check('no page errors',errors.length===0,errors);check('no unexpected failed requests',requestFailures.length===0,requestFailures);
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'PASS',origin,checks,captures,dialogs,errors,requestFailures,scope:'Disposable Chromium contexts. Native title/New Game/Continue/inline replacement/cancel/touch/keyboard/skip. Own qualified old save, controlled reset-write and media-denial fixtures, counter-only instrumentation and approved-frame seek fixtures explicitly separated. Natural full film is unretimed. No personal profile or save/physical device/full campaign claim.'},null,2)+'\n');console.log('PASS '+checks.length+' corrected entry-flow checks');
}catch(e){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({status:'FAILED',current,error:e.stack,checks,captures,dialogs,errors,requestFailures},null,2)+'\n');throw e;}finally{await browser.close();}