import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),{chromium}=require('playwright-core');
const origin=process.argv[2]||'http://127.0.0.1:8920/',out=process.argv[3]||'reports/intro-browser';
await fs.mkdir(out,{recursive:true});const checks=[],captures=[],errors=[],failures=[];let current='boot';
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function check(id,pass,observed){checks.push({id,pass:!!pass,observed});assert.ok(pass,id);}
const browser=await chromium.launch({channel:'chrome',headless:true});
const state=async p=>p.evaluate(()=>({scene:RAScenes.current(),active:RAAdventures.active(),money:RAState.get().life.resources.money,followers:RAState.get().life.resources.followers,clock:RAState.get().life.clock,ownership:RAState.get().life.ownership,flags:RAState.get().life.world.flags}));
const ready=async p=>{await p.waitForFunction(()=>window.RAOpeningCinema?.ready&&window.RAAstraCheckoutPlaceholder&&window.RANewGame);await p.evaluate(()=>document.fonts.ready);};
const instrument=async p=>p.evaluate(()=>{window.__starts=0;const fn=RANewGame.onStart;RANewGame.onStart=function(...args){__starts++;return fn.apply(this,args);};});
async function context(options={}){const c=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,...options});c.on('page',p=>{p.on('pageerror',e=>errors.push({current,text:e.message}));p.on('response',r=>{if(r.status()>=400)failures.push({current,url:r.url(),status:r.status()});});p.on('requestfailed',r=>{if(!r.url().match(/\.(mp3|ogg|wav)(\?|$)/))failures.push({current,url:r.url(),error:r.failure()?.errorText});});});return c;}
async function shot(p,name){await p.screenshot({path:path.join(out,name)});captures.push(name);}
try{
 current='first-screen-delay';const slow=await context(),s=await slow.newPage();await s.route('**/opening-assets/*.png',async r=>{await new Promise(resolve=>setTimeout(resolve,900));await r.continue();});await s.goto(origin,{waitUntil:'domcontentloaded'});
 check('cinematic-first-even-delayed',await s.evaluate(()=>!document.querySelector('#cinematicIntro').hidden&&document.querySelector('#startOverlay').hidden&&getComputedStyle(document.querySelector('#stage')).visibility==='hidden'));
 await shot(s,'first-screen.png');await ready(s);await s.keyboard.press('Enter');
 check('no-early-keyboard-game-launch',await s.evaluate(()=>document.querySelector('#startOverlay').hidden&&!RAAdventures.active()));await slow.close();
 current='responsive-title';const c=await context(),p=await c.newPage();await p.goto(origin);await ready(p);
 check('silent-cinematic-autoplay',await p.evaluate(()=>RAOpeningCinema.playing&&!RAOpeningCinema.sound&&RAOpeningCinema.audioState==='not-created'&&[...document.querySelectorAll('audio')].every(a=>a.paused)));
 const savedBefore=await p.evaluate(()=>JSON.stringify(RAState.get()));await p.locator('#skip').tap();await p.waitForTimeout(140);
 check('skip-title-lock',await p.evaluate(()=>!RAOpeningCinema.isVisible()&&!document.querySelector('#startOverlay').hidden&&!document.querySelector('#startOverlay').inert&&document.querySelector('#stage').inert&&!RAOpeningCinema.playing));
 check('skip-no-save-mutation',savedBefore===await p.evaluate(()=>JSON.stringify(RAState.get())));
 check('approved-title-copy',await p.evaluate(()=>document.querySelector('.retro-description').textContent==='Rich Alucard, a Nigerian vampire moves to LA.'&&document.querySelector('.retro-tagline').textContent==='Bite.Dance.Jug.'&&[...document.querySelectorAll('.retro-features figcaption')].map(e=>e.textContent).join('|')==='Bite|Plays|Meet Gbenga'));
 check('no-original-sample-link',await p.evaluate(()=>document.querySelectorAll('#cinematicIntro a').length===0));
 for(const [w,h] of [[320,568],[360,800],[390,844],[430,932],[1280,900],[1440,960],[844,390],[390,600]]){
  current='fit '+w+'x'+h;await p.setViewportSize({width:w,height:h});await p.locator('#startButton').scrollIntoViewIfNeeded();
  const g=await p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};};const hero=rect(document.querySelector('.retro-hero')),action=rect(document.querySelector('.retro-action'));return {overflow:document.documentElement.scrollWidth>innerWidth,hero,action,start:rect(document.querySelector('#startButton')),copy:rect(document.querySelector('.retro-copy')),rich:rect(document.querySelector('.retro-character')),scroll:[startOverlay.scrollHeight,startOverlay.clientHeight],padding:getComputedStyle(document.querySelector('.retro-action')).padding};});
  check('title-fit-and-center-'+w+'x'+h,!g.overflow&&Math.abs((g.hero.x+g.hero.width/2)-(g.action.x+g.action.width/2))<1&&g.copy.right<=g.action.x+.5&&g.action.right<=g.rich.x+.5&&g.start.height>=44&&g.start.width>=44&&g.start.x>=0&&g.start.right<=w&&g.start.y>=0&&g.start.bottom<=h+.5,g);
  await p.locator('#replayOpeningButton').scrollIntoViewIfNeeded();check('title-replay-access-'+w+'x'+h,await p.locator('#replayOpeningButton').isVisible());await p.locator('#startButton').scrollIntoViewIfNeeded();
  if([320,390,1280,844].includes(w))await shot(p,'title-'+w+'x'+h+'.png');
 }
 await p.setViewportSize({width:390,height:844});current='replay-and-start';await p.locator('#replayOpeningButton').tap();await p.waitForTimeout(120);
 check('title-replay-cinematic',await p.evaluate(()=>RAOpeningCinema.isVisible()&&RAOpeningCinema.playing&&startOverlay.hidden&&document.querySelector('#stage').inert&&document.querySelector('#retroPlayPreview').paused));
 await p.locator('#play').focus();await p.keyboard.press('r');check('r-shortcut-button-focus',await p.evaluate(()=>RAOpeningCinema.time<.15&&RAOpeningCinema.playing));await p.keyboard.press('Escape');await instrument(p);await p.locator('#startButton').focus();await p.keyboard.press('Enter');
 await p.waitForFunction(()=>RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE');
 check('native-fresh-start-once',await p.evaluate(()=>__starts===1&&!document.querySelector('#stage').inert&&startOverlay.style.display==='none'&&RAState.get().life.resources.money===40000),await state(p));
 check('hidden-title-video-paused',await p.evaluate(()=>document.querySelector('#retroPlayPreview').paused&&!RAOpeningCinema.framePending));await shot(p,'fresh-game-390.png');
 const active=await p.evaluate(()=>JSON.stringify(RAAdventures.active()));await p.reload();await ready(p);await p.locator('#skip').tap();check('continued-label',await p.locator('#startButton').innerText()==='CONTINUE');await instrument(p);await p.locator('#startButton').focus();await p.keyboard.press('Space');await p.waitForFunction(()=>__starts===1&&getComputedStyle(startOverlay).display==='none');
 check('native-space-resume-once',active===await p.evaluate(()=>JSON.stringify(RAAdventures.active()))&&await p.evaluate(()=>!document.querySelector('#stage').inert));
 await c.close();
 if(process.env.RA_INTRO_OLD_SAVE){current='old-save';const old=JSON.parse(await fs.readFile(process.env.RA_INTRO_OLD_SAVE,'utf8'));
 const oldCtx=await context();await oldCtx.addInitScript(data=>{if(window!==window.top||!/^https?:$/.test(location.protocol))return;if(!sessionStorage.getItem('intro-old-seeded')){localStorage.setItem('rich_alucard_save_v1',JSON.stringify(data));sessionStorage.setItem('intro-old-seeded','1');}},old);const q=await oldCtx.newPage();await q.goto(origin);await ready(q);const before=await state(q);await q.locator('#skip').tap();
 check('old-save-title-controls',await q.locator('#startButton').innerText()==='CONTINUE'&&await q.locator('#newGameButton').isVisible());q.once('dialog',d=>d.dismiss());await q.locator('#newGameButton').tap();
 check('cancel-new-game-preserves-state',JSON.stringify(before)===JSON.stringify(await state(q)));
 await q.locator('#startButton').tap();await q.waitForFunction(()=>getComputedStyle(startOverlay).display==='none');await q.waitForTimeout(500);const after=await state(q);
 check('old-save-continue-resources',JSON.stringify({money:before.money,followers:before.followers,ownership:before.ownership})===JSON.stringify({money:after.money,followers:after.followers,ownership:after.ownership}),{before:{money:before.money,followers:before.followers,hash:sha(JSON.stringify(before.ownership))},after:{money:after.money,followers:after.followers,hash:sha(JSON.stringify(after.ownership))}});
 check('no-cinematic-on-game-transitions',await q.evaluate(()=>!RAOpeningCinema.isVisible()&&!RAOpeningCinema.playing));await q.reload();await ready(q);await q.locator('#skip').tap();q.once('dialog',d=>d.accept());await q.locator('#newGameButton').tap();await q.waitForFunction(()=>RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE');check('confirmed-native-new-game',await q.evaluate(()=>RAState.get().life.resources.money===40000&&RAState.get().life.resources.followers===0));await oldCtx.close();}
 current='reduced-motion';const reduced=await context({reducedMotion:'reduce'}),r=await reduced.newPage();await r.goto(origin);await ready(r);check('reduced-static-first',await r.evaluate(()=>!RAOpeningCinema.playing&&!document.querySelector('#start').hidden));await r.locator('#begin').tap();await r.waitForTimeout(100);check('explicit-reduced-play',await r.evaluate(()=>RAOpeningCinema.playing));await r.locator('#skip').tap();await r.waitForTimeout(150);check('reduced-title-media-and-pulse',await r.evaluate(()=>document.querySelector('#retroPlayPreview').paused&&getComputedStyle(document.querySelector('#startButton')).animationName==='none'));await shot(r,'reduced-title.png');await reduced.close();
 current='natural-flow-performance';const natural=await context(),n=await natural.newPage();await n.goto(origin);await ready(n);await n.evaluate(()=>{window.__frameStats={last:performance.now(),deltas:[],count:0};function frame(now){__frameStats.deltas.push(now-__frameStats.last);__frameStats.last=now;__frameStats.count++;if(RAOpeningCinema.isVisible())requestAnimationFrame(frame);}requestAnimationFrame(frame);});
 const began=Date.now();await n.waitForFunction(()=>!RAOpeningCinema.isVisible(),null,{timeout:50000});check('combined-natural-end-to-title',await n.evaluate(()=>RAOpeningCinema.time===40&&!startOverlay.hidden&&document.querySelector('#stage').inert&&!RAOpeningCinema.framePending&&!RAOpeningCinema.sound),{waitMs:Date.now()-began});
 await n.waitForTimeout(1800);const perf=await n.evaluate(()=>{const d=__frameStats.deltas.slice(3).sort((a,b)=>a-b),v=document.querySelector('#retroPlayPreview').getVideoPlaybackQuality?.();return {animationFrames:__frameStats.count,p50:d[Math.floor(d.length*.5)],p95:d[Math.floor(d.length*.95)],over50ms:d.filter(x=>x>50).length,video:v?{total:v.totalVideoFrames,dropped:v.droppedVideoFrames}:null};});
 check('performance-no-heavy-stalls',perf.p95<40&&perf.over50ms<=5,perf);await instrument(n);await n.locator('#startButton').tap();await n.waitForFunction(()=>RAAdventures.active()?.id==='LEGENDARY_CORPORATE_LIFE');check('natural-title-play-game',await n.evaluate(()=>__starts===1&&!RAOpeningCinema.isVisible()&&!document.querySelector('#stage').inert));await natural.close();
 check('no-page-errors',errors.length===0,errors);check('no-unexpected-failures',failures.length===0,failures);
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'PASS',origin,checks,captures,errors,failures,scope:'Actual current runtime in disposable Chromium contexts. Native cinematic/title/START/CONTINUE/reset. Own historical QA checkpoint for save continuity; delay-only resource fixture, viewport emulation, counter-only onStart instrumentation. No physical phone/Safari/full campaign claim.'},null,2)+'\n');console.log('PASS '+checks.length+' combined opening/title/current-game checks');
}catch(e){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({status:'FAILED',current,error:e.stack,checks,captures,errors,failures},null,2)+'\n');throw e;}finally{await browser.close();}