// Freeze user-canceled audit evidence. Never modifies or deletes raw checkpoints or starts a simulation.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const dir='docs/evidence/final_a/stage5',file=`${dir}/audit-cancellation.json`;
const prior=JSON.parse((await readFile(file,'utf8')).replace(/^\uFEFF/,''));
const rowsFor=async filename=>{const raw=await readFile(filename,'utf8'),lines=raw.split('\n');if(!raw.endsWith('\n'))lines.pop();return {rows:lines.filter(Boolean).map(JSON.parse),sha256:createHash('sha256').update(raw).digest('hex'),endsWithNewline:raw.endsWith('\n')};};
const [main,supp,post]=await Promise.all([rowsFor(`${dir}/paired-checkpoint.ndjson`),rowsFor(`${dir}/completionist/paired-checkpoint.ndjson`),rowsFor(`${dir}/post-ending/post-ending-checkpoint.ndjson`)]);
const stratum=(r,planned)=>({planned,preserved:r.rows.length,canceledNotPersisted:planned-r.rows.length,labels:['before','after'].map(label=>({label,completed:r.rows.filter(x=>x.label===label).length})),fullCareers:r.rows.filter(x=>Number.isFinite(x.endingDay)).length,rawErrors:r.rows.reduce((n,x)=>n+(x.errors?.length||0),0),fatal:r.rows.filter(x=>x.fatal).length,softlocks:r.rows.reduce((n,x)=>n+(x.softlocks?.length||0),0),checkpointSha256:r.sha256,rawEndsWithNewline:r.endsWithNewline,complete:false});
const mainManifest=JSON.parse(await readFile(`${dir}/paired-run-manifest.json`,'utf8'));
const pending=(rows,personas)=>{const seen=new Set(rows.map(r=>`${r.label}|${r.persona}|${r.seed}`)),tasks=personas.flatMap(persona=>Array.from({length:10},(_,i)=>['before','after'].map(label=>({label,persona,seed:i+1}))).flat());return tasks.filter(t=>!seen.has(`${t.label}|${t.persona}|${t.seed}`));};
const mainPending=pending(main.rows,Object.keys(mainManifest.personas)),suppPending=pending(supp.rows,['completionist']);
const result={...prior,status:'USER_CANCELED',stopStatus:'stopped',frozenAt:new Date().toISOString(),reason:'Explicit user instruction to skip remaining large audits after actual completed supplemental pair established136/138 final-build OPEN exposure; remaining A23/A23R require scoped OPEN ecology3-versus4 owner ruling.',plannedOriginal:360,plannedSupplemental:20,actualOriginal:main.rows.length,actualSupplemental:supp.rows.length,original:{...stratum(main,360),workerSlotsInterrupted:2,earliestUnpersistedCaseKeys:mainPending.slice(0,2),unstartedCases:mainPending.length-2},supplemental:{...stratum(supp,20),workerSlotsInterrupted:2,earliestUnpersistedCaseKeys:suppPending.slice(0,2),unstartedCases:suppPending.length-2,lastIPCProgress:JSON.parse(await readFile(`${dir}/completionist/worker-progress.json`,'utf8'))},postEnding:{planned:18,preserved:post.rows.length,complete:post.rows.length===18,rawErrors:post.rows.reduce((n,x)=>n+x.errors.length,0),checkpointSha256:post.sha256},inflightProvenance:'Exact six stopped processes are in processScope. Two worker slots per dispatcher were interrupted. Earliest unpersisted keys follow each deterministic ordered two-worker dispatcher; canceled partial states/IPC progress are excluded from completed-case denominators. No completion is inferred for canceled work.',stopVerification:{method:'post-Stop-Process Win32_Process recheck for the exact six identity-verified IDs',remainingProcessIDs:[]},noFilesDeleted:true,noRestart:true,reporting:'Original planned360 and supplemental planned20 remain unchanged. Status.completed uses actual preserved rows; complete stays false. Post18 remains complete. All136 final-build offers use current main/current post/supplemental after only; no pilot, preserved-base witness or isolated fixture contributes.'};
await writeFile(file,JSON.stringify(result,null,1)+'\n');console.log(JSON.stringify({original:result.actualOriginal,supplemental:result.actualSupplemental,post:result.postEnding.preserved,stopStatus:result.stopStatus,canceledOriginal:result.original.canceledNotPersisted,canceledSupplemental:result.supplemental.canceledNotPersisted}));
