import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
const arg=(k,d)=>{const i=process.argv.indexOf('--'+k);return i<0?d:process.argv[i+1];},dir=path.resolve(arg('out','docs/evidence/final_a/stage5/completionist')),expected=Number(arg('expected',20)),file=arg('checkpoint','paired-checkpoint.ndjson');
const raw=await readFile(path.join(dir,file),'utf8'),lines=raw.split('\n');if(!raw.endsWith('\n'))lines.pop();const rows=lines.filter(Boolean).map(JSON.parse),healthy=rows.filter(r=>!r.fatal),labels=expected===20?['before','after']:[...new Set(healthy.map(r=>r.label))].sort();let ids=[...new Set(healthy.flatMap(r=>r.openIds))].sort();if(!ids.length){const inventory=JSON.parse(await readFile(path.resolve('docs/evidence/final_a/stage5/open-gate-inventory.json'),'utf8'));ids=inventory.adventures.map(a=>a.id).sort();}
const stats=xs=>{const a=xs.filter(Number.isFinite).sort((a,b)=>a-b),n=a.length;return {n,median:n?(n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2):null,min:n?a[0]:null,max:n?a.at(-1):null};};
const exposure=ids.map(id=>Object.assign({id},...labels.map(label=>{const g=healthy.filter(r=>r.label===label),o=g.filter(r=>r.offered[id]),done=g.filter(r=>r.completed[id]);return {[label]:{lives:g.length,offered:o.length,completed:done.length,firstOfferDay:o.length?Math.min(...o.map(r=>r.offered[id].day)):null,beforeEndingOffered:o.filter(r=>r.offered[id].day<r.endingDay).length,beforeEndingCompleted:done.filter(r=>r.completedAt?.[id]<r.endingDay).length,laterFirstOffered:o.filter(r=>r.offered[id].day>=r.endingDay).length,laterFirstCompleted:done.filter(r=>r.completedAt?.[id]>=r.endingDay).length,completionDayMeasured:done.filter(r=>Number.isFinite(r.completedAt?.[id])).length}};})));
const status={generatedAt:new Date().toISOString(),scope:'separate paired completionist through Day70; first ending preserved',expected,completed:rows.length,complete:rows.length===expected,healthy:healthy.length,fatal:rows.filter(r=>r.fatal).length,errors:healthy.reduce((n,r)=>n+r.errors.length,0),softlocks:healthy.reduce((n,r)=>n+r.softlocks.length,0),endingDays:[...new Set(healthy.map(r=>r.endingDay))],finalDays:[...new Set(healthy.map(r=>r.final.day))],openAdventures:ids.length,labels:labels.map(label=>({label,lives:healthy.filter(r=>r.label===label).length,offered:exposure.filter(x=>x[label].offered).length,completed:exposure.filter(x=>x[label].completed).length,neverOffered:exposure.filter(x=>!x[label].offered).map(x=>x.id)}))};
Object.assign(status,{fullCareers:healthy.filter(r=>Number.isFinite(r.endingDay)).length,throughDay70:healthy.filter(r=>r.final.day===71&&r.daily.length===70).length});if(expected===20)status.complete=status.complete&&status.fullCareers===20&&status.throughDay70===20;
const metrics=labels.map(label=>{const g=healthy.filter(r=>r.label===label),hall=g.filter(r=>r.ownership?.['room:party_hall']);return {label,lives:g.length,endingDay:stats(g.map(r=>r.endingDay)),moneyAtFirstEnding:stats(g.map(r=>r.atFirstEnding?.money)),netWorthAtFirstEnding:stats(g.map(r=>r.atFirstEnding?.netWorth)),laterFinalMoney:stats(g.map(r=>r.final.money)),laterFinalNetWorth:stats(g.map(r=>r.final.netWorth)),partyHallPaidDay:stats(hall.map(r=>r.ownership['room:party_hall'])),partyHallBy30:hall.filter(r=>r.ownership['room:party_hall']<=30).length,partyHallPreEnding:hall.filter(r=>r.ownership['room:party_hall']<r.endingDay).length,elapsedSeconds:stats(g.map(r=>r.elapsedSeconds))};});
const csv=(h,data)=>[h,...data].map(row=>row.map(v=>{const s=v==null?'':String(v);return /[",\r\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s;}).join(',')).join('\n')+'\n';
await writeFile(path.join(dir,'population-status.json'),JSON.stringify(status,null,1)+'\n');await writeFile(path.join(dir,'population-tables.json'),JSON.stringify({status,metrics,exposure},null,1)+'\n');
const cols=['lives','offered','completed','firstOfferDay','beforeEndingOffered','beforeEndingCompleted','laterFirstOffered','laterFirstCompleted','completionDayMeasured'];
await writeFile(path.join(dir,'exposure.csv'),csv(['id',...labels.flatMap(l=>cols.map(k=>l+'_'+k))],exposure.map(r=>[r.id,...labels.flatMap(l=>cols.map(k=>r[l][k]))])));
const cells=s=>s.n?`${s.median} (${s.min}–${s.max}); n=${s.n}`:'not measured';
await writeFile(path.join(dir,'population-report.md'),`# Separate completionist observations\n\n**${status.complete?'COMPLETE':'IN PROGRESS'}**: ${rows.length}/${expected} cases; ${status.fatal} fatal,${status.errors} branch observations,${status.softlocks} pending-play observations. This additional policy never replaces or changes the original360 or post18. ${expected===1?'This is the feasibility pilot, excluded from the final20.':''}\n\nFirst ending days: ${status.endingDays.join(', ')}. Later cursor days: ${status.finalDays.join(', ')}. Final later wealth includes continuation through Day70. The exposure CSV distinguishes first offers/completions before the actual ending from additional first offers/completions later; an absent completion-day field is reported as unmeasured, never inferred from a first offer. No isolated fixture enters these counts.\n\n| Build | Cases | First ending | Cash at first ending | Net worth at first ending | Cash later | Net worth later | Paid Hall day | Hall by30 |\n|---|---:|---|---|---|---|---|---|---|\n${metrics.map(m=>`| ${m.label} | ${m.lives} | ${cells(m.endingDay)} | ${cells(m.moneyAtFirstEnding)} | ${cells(m.netWorthAtFirstEnding)} | ${cells(m.laterFinalMoney)} | ${cells(m.laterFinalNetWorth)} | ${cells(m.partyHallPaidDay)} | ${m.partyHallBy30}/${m.lives} |`).join('\n')}\n\n${status.labels.map(x=>`- ${x.label}: ${x.offered}/${ids.length} observed offers and ${x.completed}/${ids.length} completed through Day70 in ${x.lives} measured lives. Missing: ${x.neverOffered.join(', ')||'none'}.`).join('\n')}\n\nEarned-world files are actual final production state from these cases; they contain no extra eligibility fixtures. Generic skill, legacy public callback outcome and presentation seams are declared in index.md. These careers do not establish browser or minigame input stability.\n`);console.log(JSON.stringify(status));
