#!/usr/bin/env node
// Read persisted career rows and OPEN provenance. Fixtures never contribute to exposure counts.
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),dir=path.join(repo,'docs/evidence/final_a/stage5');
const json=async file=>JSON.parse(await readFile(path.join(dir,file),'utf8'));
const readRows=async file=>{const raw=await readFile(path.join(dir,file),'utf8'),lines=raw.split('\n');if(!raw.endsWith('\n'))lines.pop();return lines.filter(Boolean).map(JSON.parse).filter(r=>!r.fatal);};
const [inventory,historical,isolated,main,post]=await Promise.all([json('open-gate-inventory.json'),json('reachability-after.json'),json('isolated-gate-probes.json'),readRows('paired-checkpoint.ndjson'),readRows('post-ending/post-ending-checkpoint.ndjson')]);
let completionist=[],completionistStarted=false;try{completionist=await readRows('completionist/paired-checkpoint.ndjson');completionistStarted=true;}catch(e){if(e.code!=='ENOENT')throw e;}
const exactId=(s,id)=>typeof s==='string'&&new RegExp('(?:[\'"`])'+id+'(?:[\'"`])').test(s);
const overrides={
 A00:{route:'Fresh opening controller → THE GOLDFISH YEARS actual A00 graph',why:'Every measured life walks the actual A00 graph; subsequent legacy throne encounter is explicitly outside the main result/presentation scope.'},
 A51:{route:'GO SOMEWHERE → TACOS on a real rain night → CANCIÓN NIGHT chain',why:'Authored TACOS completion chains only on rain and while A51 remains available; current observations are actual graph selections.'},
 A56:{route:'JOLLOF WARS actual final win → LIL SMACK #5 chain',why:'Requires the authored tournament final-win outcome; main minigame skills are declared result substitutes, not browser input proofs.'},
 A55:{route:'VampGPT → MEET PEOPLE → FIND A PARTY after Ogun rave and first Lo party',why:'Real party selector and canonical rave flag choose this one-time second rave before repeatable human/vampire parties.'},
 ROOFTOP_DTLA:{route:'VampGPT → MEET PEOPLE → FIND A PARTY → rotating rooftop party',why:'Real party rotation and the capped people-lane display control this repeatable entry.'},
 A17:{route:'Lose a real combat encounter with penalty → RADefeat.apply → blood-bank wake',why:'Main generic fight-result seam skips the production defeat callback; isolated real callback proves pending wake and cash debit.'},
 A23:{route:'Paid castle HOOKAH roof scene + ecology level≥2 → wake',why:'Available OPEN callback contracts/current producer evidence give released assistant2 + kept daughter1 = pressure3, below existing warning4. Isolated production saturation stays3 over5 wakes. No additional OPEN producer was found in the scoped search; no claim about protected internals. Owner ruling required; fixtures do not count as career offers.'},
 A23R:{route:'A23 done → Bruce A19 reveals Armory → A24 → buy a gun → WHAT WE ON rematch',why:'Depends on A23 and its scoped OPEN3-versus4 pressure gap, then actual gun preparation. Historical/isolated rematch wiring proofs pass separately; no threshold/contribution change or fixture count repairs exposure.'},
 A36:{route:'TOUGE app → TANDEM after A13 and car ownership',why:'Main policy chooses the general place/lane TANDEM_BATTLE, not this app action. Isolated actual app callback chooses A36.'},
 A39:{route:'Buy MAID QUARTERS ($40,000) → CASTLE room before Marisol hired',why:'Only explorer policy targets this room; a missing paid purchase/selection does not establish an unreachable gate.'},
 A57:{route:'Travel by owned car → real route renderer calls RANodd.maybeStop → wake',why:'Main route choice always walks, so it never produces drive notifications. Separate real Nodd callback proves the wake route.'},
 A53:{route:'Authored Day57 wake; adventure gate permits Day≥57',why:'Every measured main first ending is Day36. Day57 content is outside this main measurement window and is counted only in the separate continuation.'},
 A_CAMMILE1:{route:'Legacy JDM owner defeated/daughter meeting → GO SOMEWHERE docks',why:'Main legacy Supra computeCompletionState pays the real price and grants the vehicle, but does not call ownerDefeated/recordDaughterMeeting. Contact producer is outside the main legacy outcome substitute.'},
 RE_VIEWING:{route:'REALMONEYREALESTATE → SEE IT WITH SHANNON on a later listing after Paloma',why:'Main buys the legacy Paloma property and collects real rent; it does not select subsequent listing viewings. Isolated real app callback passes.'},
 SHOP:{route:'GO SOMEWHERE → FLORIST ON SUNSET custom-go handler',why:'Main place policy only selects adventure-valued destinations, skipping custom-go florist. Separate ordinary fresh menu callback passes.'},
 THRONE:{route:'CASTLE → always available THRONE ROOM',why:'Main opening marks throneDone as a routing fixture and does not visit this repeatable room adventure. Isolated ordinary room route passes.'},
 ARMORY_WALL:{route:'Buy ARMORY WALL ($60,000) → CASTLE room custom handler',why:'Main ignores custom-go room handlers. Separate continuation visits actual owned room handlers; isolated paid route proves the entry.'},
 COFFIN:{route:'Buy COFFIN UPGRADE ($200,000) → CASTLE custom room handler',why:'Main ignores custom-go room handlers. Actual affordability/purchase must be read from career ownership; isolated paid route is not affordability evidence.'},
 FISHTANK:{route:'Buy FISH TANK ($400,000) → CASTLE custom room handler',why:'Main ignores this custom-go room handler. Actual ownership timing is reported separately; continuation and isolated paid entry proofs do not count before ending.'},
 KITCHEN:{route:'Buy KITCHEN ($85,000) → CASTLE room',why:'Main purchase policy records price and ownership but does not generally revisit owned rooms; continuation adds actual owned room entries.'},
 MOVIE:{route:'Buy MOVIE ROOM ($110,000) → CASTLE room',why:'Requires an observed paid purchase and room selection; separate continuation adds actual owned room entries.'},
 GARAGE_VIEW:{route:'Buy GARAGE ($150,000) → CASTLE room',why:'Requires an observed paid purchase and room selection; separate continuation adds actual owned room entries.'},
 ROOST:{route:'Own a dragon and buy DRAGON ROOST ($90,000) → CASTLE room',why:'Requires both paid ownership and dragon care; continuation adds actual owned room entries and actual dragon care.'},
 MAID:{route:'Buy MAID QUARTERS → A39 hires Marisol → same CASTLE room',why:'Only explorer targets this room, and hiring must occur before repeatable MAID can be selected. Historical paid room route proof passes.'},
 A26:{route:'Buy PARTY HALL ($250,000) after recorded Ogun rave/hosting unlock → CASTLE hall',why:'Paid hall ownership is a separate economic observation; only relevant policies target it. Read ownership.csv for actual purchase timing.'},
 HOST:{route:'After A26 → PARTY HALL repeatable party themes',why:'Depends on paid hall ownership, completion of A26 and selection of a party theme. Historical route proof passes.'},
 A_JADE1:{route:'PARTY HALL → HOST theme DRAGON NIGHT → one-time chain',why:'Requires a paid hall and that specific theme; main policy variety need not choose it. Historical player route proof passes.'},
 A32:{route:'Dragon majestic with care streak≥5 → wake',why:'Main does not perform a sustained dragon care policy before its first ending. Continuation adds actual care without stage injection.'},
 A33:{route:'Street reputation≥2 → wake',why:'Actual reputation progression and higher-priority wakes determine timing; absence is not an unreachable gate.'},
 A27:{route:'Morning after an actual partyNight → wake',why:'Depends on paid hall/theme or party outcome flags and wake priority; inspect actual A26/HOST observations rather than assuming possession implies partyNight.'},
 RB_DELIVERY:{route:'RICHBOIIMPORTS actual purchase → delivery adventure',why:'Requires the $500,000 net-worth/duchessTease app unlock and a paid catalog purchase; policy ownership rows distinguish pre-ending from later access.'}
};
for(const tag of ['NNEKA','CAMMILE','MAZDA','JUNE','PATRICE'])for(const level of [1,2,3]){
 const id=`ARC_${tag}_${level}`;if(!inventory.adventures.some(a=>a.id===id))continue;
 const producer={NNEKA:'blood-bank A17 meeting',CAMMILE:'legacy JDM daughter meeting',MAZDA:'majestic dragon A32 meeting',JUNE:'June A37 party meeting',PATRICE:'completed fourth Waffle Saga A44_N4'}[tag];
 overrides[id]={route:`${producer} → real dates → relationship level ${level+1} → ordered InstaHoe DM`,why:`Requires ${producer}, actual relationship progression and prior arc completion. Main capped daily dates prioritize other contacts; a missing contact producer or unmet level is a policy/measurement limit. Separate real dated-callback/DM graph proof passes; it is not career exposure.`};
}
for(const a of inventory.adventures.filter(x=>x.id.startsWith('F15_')))overrides[a.id]={route:'Paid F06 MAKE IT RAIN spend for this club → sequential F15 InstaHoe DM',why:'Feature enabled; thresholds are existing $10k/$35k/$80k/$150k cumulative real paid spend with prior-level completion and one-per-wake arbitration. Only one club per designated trap policy. Main uses real F06 spend; missing level is not an unreachable verdict.'};
const groups={before:main.filter(r=>r.label==='before'),after:main.filter(r=>r.label==='after'),post,completionistBefore:completionist.filter(r=>r.label==='before'),completionistAfter:completionist.filter(r=>r.label==='after')};
const census=(id,rows)=>{const offered=rows.filter(r=>r.offered?.[id]),done=rows.filter(r=>r.completed?.[id]);return {lives:rows.length,offered:offered.length,completed:done.length,firstOfferDay:offered.length?Math.min(...offered.map(r=>r.offered[id].day)):null,beforeEndingOffered:offered.filter(r=>r.offered[id].day<r.endingDay).length,laterFirstOffered:offered.filter(r=>r.offered[id].day>=r.endingDay).length,beforeEndingCompletedMeasured:done.filter(r=>r.completedAt?.[id]<r.endingDay).length,laterFirstCompletedMeasured:done.filter(r=>r.completedAt?.[id]>=r.endingDay).length,completionDayMeasured:done.filter(r=>Number.isFinite(r.completedAt?.[id])).length};};
const rows=inventory.adventures.slice().sort((a,b)=>a.id.localeCompare(b.id)).map(a=>{
 const wake=inventory.wake.filter(w=>w.adventure===a.id),wants=inventory.wants.filter(w=>w.adventure===a.id||exactId(w.adventure,a.id)),places=(inventory.places||[]).filter(p=>p.adventure===a.id||exactId(p.adventure,a.id)||exactId(p.go,a.id)),incoming=(inventory.chainEntries||[]).filter(x=>x.target===a.id);
 const old=historical.rows?.[a.id]||{},proofs=(historical.proofs||[]).filter(p=>p.name===a.id||new RegExp('(?:^|[^A-Z0-9_])'+a.id+'(?:$|[^A-Z0-9_])').test(p.name));
 const callbacks=isolated.proofs.filter(p=>p.ids.includes(a.id)),seen=Object.fromEntries(Object.entries(groups).map(([k,g])=>[k,census(a.id,g)]));
 const route=overrides[a.id]?.route||proofs.map(p=>p.route).join('; ')||[...places.map(p=>`${p.hidden?'CASTLE/hidden':'GO SOMEWHERE'}: ${p.id}`),...wants.map(w=>`${w.thread?'InstaHoe/':''}WHAT WE ON: ${w.id}`),...wake.map(w=>'wake trigger'),...incoming.map(x=>`${x.from} → ${x.choice||x.node+' authored chain'}`),...(old.routes||[]).filter(x=>!['place','want/dm','wake','chain'].includes(x))].join('; ')||'Registered OPEN entry; see historical route classifier/source gate';
 const mainObserved=seen.after.offered>0;
 const status=mainObserved?'OBSERVED final build before first ending':seen.completionistAfter.beforeEndingOffered?'OBSERVED final build in supplemental pre-ending policy':seen.post.offered||seen.completionistAfter.offered?'OBSERVED final build only in separate continuation':callbacks.length||proofs.length?'UNOBSERVED final build in careers; separate player/callback proof passes':seen.before.offered||seen.completionistBefore.offered?'OBSERVED preserved base only; final build unobserved':'UNOBSERVED; source entry identified, no supplemental dynamic proof';
 return {id:a.id,lane:a.lane,scope:a.scope,repeatable:a.repeatable,normalPlayerEntry:route,status,whyUnobservedOrCoverageLimit:overrides[a.id]?.why||(mainObserved?'Actual career offer/selection counts below; zero completion in an offered life may be policy selection rather than a gate defect.':'No main policy selected or produced this route in the measured window; exact gates below identify prerequisites. Unobserved is not an unreachable verdict.'),...seen,availableGate:a.available,wakeGates:wake,wantGates:wants,placeGates:places,incomingChains:incoming,historicalRouteCategories:old.routes||[],historicalProofs:proofs.map(p=>({name:p.name,route:p.route,seeds:p.seeds,result:p.result})),supplementalProbes:callbacks.map(p=>({route:p.route,seeds:p.seeds,status:p.status,evidence:p.evidence}))};
});
const status={generatedAt:new Date().toISOString(),mainCompleted:main.length,mainExpected:360,postCompleted:post.length,postExpected:18,openIds:rows.length,mainFirstEndings:[...new Set(main.map(r=>r.endingDay))],mainOfferedBefore:rows.filter(r=>r.before.offered).length,mainOfferedAfter:rows.filter(r=>r.after.offered).length,postOffered:rows.filter(r=>r.post.offered).length,mainMissing:rows.filter(r=>!r.before.offered&&!r.after.offered).map(r=>r.id),noCareerOfferButSupplementalPassed:rows.filter(r=>!r.before.offered&&!r.after.offered&&!r.post.offered&&(r.supplementalProbes.length||r.historicalProofs.length)).map(r=>r.id)};
Object.assign(status,{completionistCompleted:completionist.length,completionistExpected:completionistStarted?20:0,completionistOfferedBefore:rows.filter(r=>r.completionistBefore.offered).length,completionistOfferedAfter:rows.filter(r=>r.completionistAfter.offered).length,finalBuildCareerUnionOffered:rows.filter(r=>r.after.offered||r.post.offered||r.completionistAfter.offered).length,finalBuildCareerUnionMissing:rows.filter(r=>!r.after.offered&&!r.post.offered&&!r.completionistAfter.offered).map(r=>r.id)});
status.noCareerOfferButSupplementalPassed=rows.filter(r=>!r.after.offered&&!r.post.offered&&!r.completionistAfter.offered&&(r.supplementalProbes.length||r.historicalProofs.length)).map(r=>r.id);
await writeFile(path.join(dir,'open-route-status.json'),JSON.stringify({method:'All138 OPEN IDs. Career observations have independent measured-life denominators; historical proofs and isolated declared fixtures are never added to exposure/economy. Source gate provenance is exact current runtime function text. No unreachable verdict is inferred from non-observation.',status,rows},null,1)+'\n');
const csv=(head,data)=>[head,...data].map(row=>row.map(v=>{const s=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);return /[",\r\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s;}).join(',')).join('\n')+'\n';
const censusColumns=['lives','offered','completed','beforeEndingOffered','laterFirstOffered','beforeEndingCompletedMeasured','laterFirstCompletedMeasured','completionDayMeasured'];
await writeFile(path.join(dir,'open-route-status.csv'),csv(['id','normal_player_entry','status',...Object.keys(groups).flatMap(k=>censusColumns.map(x=>k+'_'+x)),'historical_proof','supplemental_probe','why_unobserved_or_limit','adventure_gate','wake_gates','want_gates'],rows.map(r=>[r.id,r.normalPlayerEntry,r.status,...Object.keys(groups).flatMap(k=>censusColumns.map(x=>r[k][x])),r.historicalProofs.map(x=>x.name+': '+x.result).join('; '),r.supplementalProbes.map(x=>x.status).join('; '),r.whyUnobservedOrCoverageLimit,r.availableGate,r.wakeGates,r.wantGates])));
const cell=s=>String(s??'—').replaceAll('|','\\|').replaceAll('\n',' ');
await writeFile(path.join(dir,'open-route-status.md'),`# All OPEN routes and observation boundaries\n\n${main.length}/360 main careers and ${post.length}/18 separate continuations persisted at ${status.generatedAt}. **${main.length===360&&post.length===18?'COMPLETE':'IN PROGRESS'}**. There are exactly ${rows.length} runtime OPEN IDs. Main life denominators: before ${groups.before.length}/180, after ${groups.after.length}/180. Continuations: ${groups.post.length}/18 through Day70. First ending days observed: ${status.mainFirstEndings.join(', ')}. No fixture count contributes to these denominators.\n\nEach numeric cell is offered/completed lives. The JSON/CSV carries exact adventure, wake, want and place gate provenance plus fixture declarations. Historical proofs come from reachability-after.json; current callback proofs come from isolated-gate-probes.json. Neither establishes population affordability or browser stability. Missing career exposure is a measured gap, not proof that a route is impossible.\n\n| ID | Normal player entry | Before O/C | After O/C | Post O/C | Separate proof | Classification / limit |\n|---|---|---:|---:|---:|---|---|\n${rows.map(r=>`| ${r.id} | ${cell(r.normalPlayerEntry)} | ${r.before.offered}/${r.before.completed} | ${r.after.offered}/${r.after.completed} | ${r.post.offered}/${r.post.completed} | ${cell([r.historicalProofs.length?'historical PASS':null,r.supplementalProbes.length?'isolated callback PASS':null].filter(Boolean).join('; ')||'none')} | ${cell(r.status+'; '+r.whyUnobservedOrCoverageLimit)} |`).join('\n')}\n`);
const mdFile=path.join(dir,'open-route-status.md');
await writeFile(mdFile,(await readFile(mdFile,'utf8'))+`\n## Final-build union and separate supplemental denominator\n\nThe final-build career union uses main after, current post18 and supplemental after only: currently${status.finalBuildCareerUnionOffered}/${rows.length} observed IDs. Preserved-base witnesses, feasibility pilots and all historical/isolated fixtures are excluded. Missing final-build career offers: ${status.finalBuildCareerUnionMissing.join(', ')||'none'}.\n\nSupplemental population: ${completionist.length}/${status.completionistExpected} fresh cases; before ${groups.completionistBefore.length}/10 and after ${groups.completionistAfter.length}/10 throughDay70. Its full per-ID numeric columns are in this JSON/CSV and completionist/exposure.csv, separating first offers and measured first completions before the actual ending from later continuation. Original completion days without an explicit field remain unmeasured rather than inferred from their offer day. The exposure target remains unmet for any unobserved final-build ID.\n`);
console.log(JSON.stringify(status));
