import fs from 'node:fs/promises';import path from'node:path';import assert from'node:assert/strict';import{createRequire}from'node:module';const require=createRequire(import.meta.url),{chromium}=require('playwright-core');
const base=process.argv[2]||process.env.RA_DRIVING_ORIGIN||'http://127.0.0.1:8918/',out=process.argv[3]||'reports/driving-browser';await fs.mkdir(out,{recursive:true});
const ids=(process.env.RA_DRIVING_IDS||'touge').split(','),checks=[],captures=[],errors=[],failed=[];
const browser=await chromium.launch({channel:'chrome',headless:true});let current='boot';
function check(name,width,actual,expected){assert.deepEqual(actual,expected,name);checks.push({name,width,actual,expected,pass:true});}
try{
 for(const [w,h]of [[360,800],[390,844],[430,932],[1280,900]]){
  const ctx=await browser.newContext({viewport:{width:w,height:h},hasTouch:w<500,isMobile:w<500}),p=await ctx.newPage();p.on('pageerror',e=>errors.push({width:w,text:e.message}));p.on('response',r=>{if(r.status()>=400&&/\.(js|css|png|mjs)(\?|$)/.test(r.url()))failed.push({url:r.url(),status:r.status()});});
  current='load '+w;await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.RAAstraCheckoutPlaceholder);await p.locator('#startButton').click();
  await p.evaluate(()=>{RAAdventures.abandon();RAState.patch(d=>{d.life.clock.started=true;d.life.world.flags.throneDone=true;});RAScenes.go('bedroom');});await p.waitForTimeout(200);
  const cdp=await ctx.newCDPSession(p),canvas=p.locator('.ra-minigame-stage canvas');let bounds;
  const point=(id,x,y)=>({id,x:bounds.x+x*bounds.width/270,y:bounds.y+y*bounds.height/480});
  const touch=async(type,points)=>{await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});await p.waitForTimeout(90);};
  const state=()=>p.evaluate(()=>{const d=document.querySelector('.ra-minigame-stage').dataset;return{steer:Number(d.steer),throttle:Number(d.throttle),brake:d.ebrake==='true',pointers:Number(d.pointers),phase:d.phase,speed:Number(d.speed)};});
  async function launch(id,params={}){
   await p.evaluate(({id,params})=>{window.__driveResult=null;RAMinigames.launch(id,{car:'s15',seed:31,durationSeconds:10,...params},{host:document.getElementById('game'),returnScene:'bedroom'}).then(r=>window.__driveResult=r);},{id,params});
   await p.waitForFunction(()=>document.querySelector('.ra-minigame-start')||document.querySelector('.ra-minigame-stage canvas'));const hasCard=await p.locator('.ra-minigame-start').count();const rule=hasCard?await p.locator('.ra-minigame-rule-text').innerText():await p.evaluate(id=>RAMinigames.get(id).rule,id);check(id+' visible hold instruction',w,/Hold (LEFT|GAS)/.test(rule),true);if(w===390&&id===ids[0]&&hasCard){const file='390-rule.png';await p.screenshot({path:path.join(out,file)});captures.push({file,width:w,phase:'rule'});}
   if(hasCard)await p.locator('.ra-minigame-start').click();await canvas.waitFor();await p.waitForTimeout(220);bounds=await canvas.boundingBox();check(id+' all controls fit viewport',w,bounds.y+474*bounds.height/480<=h+.5,true);check(id+' minimum touch button height',w,46*bounds.height/480>=44,true);
   await p.evaluate(()=>{window.__drivePids=[];document.querySelector('.ra-minigame-stage canvas').addEventListener('pointerdown',e=>__drivePids.push(e.pointerId));});
  }
  current='native holds '+w;await launch(ids[0]);check('cruise unchanged',w,(await state()).throttle,.5);
  const l=point(1,35,450),g=point(2,165,450),b=point(3,231,450),r=point(4,101,450);
  await touch('touchStart',[l]);check('stationary LEFT',w,(await state()).steer,-1);
  await touch('touchStart',[l,g]);let s=await state();check('LEFT + GAS',w,[s.steer,s.throttle,s.pointers],[-1,1,2]);
  if(w===390){const file='390-left-gas-held.png';await p.screenshot({path:path.join(out,file)});captures.push({file,width:w,phase:'actual two-finger stationary hold'});}
  await touch('touchStart',[l,g,b]);s=await state();check('three independent holds',w,[s.steer,s.throttle,s.brake,s.pointers],[-1,1,true,3]);
  await touch('touchEnd',[l]);s=await state();check('release steer preserves gas/brake',w,[s.steer,s.throttle,s.brake,s.pointers],[0,1,true,2]);
  await touch('touchEnd',[g]);s=await state();check('release gas preserves brake/cruise',w,[s.throttle,s.brake,s.pointers],[.5,true,1]);
  await touch('touchCancel',[]);s=await state();check('native pointer cancellation clears all',w,[s.steer,s.throttle,s.brake,s.pointers],[0,.5,false,0]);
  await touch('touchStart',[l,r]);check('opposed steering neutral',w,(await state()).steer,0);await touch('touchEnd',[l]);check('remaining RIGHT holds',w,(await state()).steer,1);await touch('touchEnd',[]);
  const b2=point(5,230,457);await p.keyboard.down(' ');await touch('touchStart',[b,b2]);await touch('touchEnd',[b]);check('one brake pointer released',w,(await state()).brake,true);await touch('touchEnd',[]);check('keyboard brake survives pointer release',w,(await state()).brake,true);await p.keyboard.up(' ');await p.waitForTimeout(90);check('final brake release',w,(await state()).brake,false);
  await touch('touchStart',[l]);await touch('touchMove',[{...l,x:l.x+1}]);await p.evaluate(()=>{const c=document.querySelector('.ra-minigame-stage canvas');const id=__drivePids.at(-1);c.releasePointerCapture(id);});await touch('touchMove',[{...l,x:l.x+2}]);check('lost pointer capture clears steer',w,(await state()).steer,0);await touch('touchEnd',[]);
  await touch('touchStart',[g]);await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.waitForTimeout(90);s=await state();check('blur cleanup',w,[s.steer,s.throttle,s.brake,s.pointers],[0,.5,false,0]);await touch('touchEnd',[]);
  await p.keyboard.down('ArrowRight');await p.keyboard.down('ArrowUp');await p.keyboard.down(' ');await p.waitForTimeout(90);s=await state();check('real keyboard controls',w,[s.steer,s.throttle,s.brake],[1,1,true]);await p.keyboard.up('ArrowRight');await p.keyboard.up('ArrowUp');await p.keyboard.up(' ');await p.waitForTimeout(90);s=await state();check('keyboard release',w,[s.steer,s.throttle,s.brake],[0,.5,false]);
  current='results/restart '+w;await p.waitForFunction(()=>document.querySelector('.ra-minigame-stage')?.dataset.phase==='results',null,{timeout:16000});s=await state();check('run ends with released pointers',w,[s.steer,s.brake,s.pointers],[0,false,0]);
  if(w===390){const file='390-results.png';await p.screenshot({path:path.join(out,file)});captures.push({file,width:w,phase:'natural short-parameter practice result'});}
  await p.keyboard.press('r');await p.waitForTimeout(90);check('native practice retry',w,(await state()).phase,'run');await touch('touchStart',[g]);check('retry accepts stationary gas',w,(await state()).throttle,1);await touch('touchEnd',[]);await p.locator('.ra-minigame-quit').click();await p.waitForFunction(()=>window.__driveResult);check('QUIT cleanup',w,await p.evaluate(()=>RAMinigames.active()),null);
  await launch(ids[0],{durationSeconds:.7,noAssist:true});check('noAssist unchanged',w,(await state()).throttle,0);await p.waitForFunction(()=>document.querySelector('.ra-minigame-stage')?.dataset.phase==='results');bounds=await canvas.boundingBox();await touch('touchStart',[point(8,200,416)]);await touch('touchEnd',[]);await p.waitForFunction(()=>window.__driveResult);check('native DONE',w,await p.evaluate(()=>__driveResult.quit),false);
  for(const id of ids.slice(1)){current=id+' '+w;await launch(id,{durationSeconds:2,tandem:{rival:'TEST',role:'lead',threshold:650}});bounds=await canvas.boundingBox();await touch('touchStart',[point(11,100,450),point(12,165,450)]);s=await state();check(id+' generated input',w,[s.steer,s.throttle],[1,1]);if(w===390){const file='390-'+id+'-held.png';await p.screenshot({path:path.join(out,file)});captures.push({file,width:w,phase:'declared generated-mount entry; native touch'});}await touch('touchCancel',[]);s=await state();check(id+' cancellation',w,[s.steer,s.brake,s.pointers],[0,false,0]);await p.locator('.ra-minigame-quit').click();await p.waitForFunction(()=>window.__driveResult);check(id+' inherited quit',w,await p.evaluate(()=>__driveResult.quit),true);}
  await ctx.close();console.log('PASS driving controls '+w+'x'+h);
 }
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await fs.writeFile(path.join(out,'results.json'),JSON.stringify({status:'PASS',base,ids,checks,captures,errors,failedRequests:failed,scope:'Disposable Chromium contexts. Native touch via CDP/keyboard/START/results/retry/DONE/QUIT. Minigame entry and duration/noAssist/tandem parameters are declared component fixtures; no earned-route/full campaign/physical device claim. Blur is a dispatched lifecycle event; lost capture uses native browser releasePointerCapture.'},null,2)+'\n');console.log('PASS '+checks.length+' driving input checks');
}catch(e){await fs.writeFile(path.join(out,'failure.json'),JSON.stringify({current,error:e.stack,checks,errors,failed},null,2));throw e;}finally{await browser.close();}
