import fs from 'node:fs';
import {serve,loadPlaywright} from '../tests/f05/_browser-lib.mjs';
const server=await serve(),{chromium}=loadPlaywright(),browser=await chromium.launch({headless:true,executablePath:process.env.RA_CHROMIUM_PATH});
const resume=process.argv.includes('--resume-shell');
const prior=resume?JSON.parse(fs.readFileSync('docs/evidence/build2/diagnostic/tap-census-progress.json','utf8')).rows.filter(r=>r.screen==='review controls'||r.screen.startsWith('owned Armory')||r.screen==='attached Armory'||(!r.screen.includes(' ')&&!r.screen.startsWith('minigame'))):[];
const page=await browser.newPage({viewport:{width:1040,height:1000}}),rows=[...prior],errors=[],screens=new Set(prior.map(r=>r.screen));
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept('CENSUS'));
const count=async f=>f.evaluate(()=>Object.entries(RAAudio.describe().plays).filter(([id])=>/^(UI_|PHONE_|APP_UNLOCK)/.test(id)).reduce((n,[id,k])=>n+k,0));
let f;
async function tap(screen,locator){const label=await locator.getAttribute('data-phone-action')||await locator.getAttribute('data-c2')||await locator.getAttribute('aria-label')||await locator.textContent();const before=await count(f);await locator.click({timeout:10000});await page.waitForTimeout(300);const after=await count(f);rows.push({screen,element:String(label).trim(),sound:after>before,starts:after-before});screens.add(screen);fs.writeFileSync('docs/evidence/build2/diagnostic/tap-census-progress.json',JSON.stringify({tapped:rows.length,withSound:rows.filter(r=>r.sound).length,rows,errors}));}
async function restore(){await page.waitForTimeout(200);await f.evaluate(async()=>{RAMinigames.quitActive();if(RACombat2.active())RACombat2.active().abort();await RAPhone.close();RAAdventures.abandon();RAState.write(localStorage,__tapBase,false);RAState.load();RAAdventures.abandon();RALife.setFlag('wakeTrigger',null);await RAScenes.go('bedroom');RAAudio.setMuted(false);if(RAPhone.isOpen())throw Error('phone overlay failed to close');});}
async function phonePath(path){await restore();await f.evaluate(()=>{RAPhone.open();RAPhone.home();});await page.waitForTimeout(260);for(const action of path){await f.locator(`[data-phone-action=${JSON.stringify(action)}]`).first().click({force:true});await page.waitForTimeout(30);}}
async function inventory(sel){return f.locator(sel).evaluateAll(es=>es.filter(e=>!e.disabled&&e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map((e,i)=>({i,id:e.id,tag:e.tagName,action:e.getAttribute('data-phone-action'),c2:e.getAttribute('data-c2'),jdm:e.getAttribute('data-jdm-action'),property:e.getAttribute('data-property-action'),bus:e.getAttribute('data-audio-bus'),toggle:e.getAttribute('data-audio-toggle'),label:e.getAttribute('aria-label')||e.textContent})));}
try{
 await page.goto(`http://127.0.0.1:${server.address().port}/tools/build2/review.html`);await page.click('#seed');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Review save prepared'));await page.click('#armory');f=page.frames().find(x=>x!==page.mainFrame());await f.waitForSelector('.ia-gun');
 await f.evaluate(async()=>{RAAudio.unlock();await RAAudio.preloadScene(['UI_TAP','UI_BACK','UI_CONFIRM','UI_ERROR','PHONE_OPEN','PHONE_CLOSE','PHONE_APP_OPEN']);for(const a of RAPhoneApps.list())RALife.unlockApp(a.id,{silent:true});RAIronMoves.unlock();window.__tapBase=structuredClone(RAState.get());});
 if(!resume){
 // Browser controls, including all candidate and reserved tour buttons; seed reload is tested separately at the end.
 await page.click('#reserved');for(const id of ['armory','moves','fight','tour',...await page.locator('[data-candidate],[data-reserved]').evaluateAll(es=>es.map((e,i)=>{e.id='audio-control-'+i;return e.id;}))]){await restore();await tap('review controls',page.locator('#'+id));}
 const queue=[[]],seen=new Set();
 for(let qi=0;qi<queue.length;qi++){
  const path=queue[qi];await phonePath(path);const key=await f.evaluate(()=>RAPhone.page());if(seen.has(key))continue;seen.add(key);console.log('SCREEN',key);
  const buttons=await inventory('#phoneOverlay button,#phoneOverlay input');
  for(const b of buttons){await phonePath(path);const loc=b.id?f.locator('#'+b.id):b.action?f.locator(`[data-phone-action=${JSON.stringify(b.action)}]`).first():b.jdm?f.locator(`[data-jdm-action=${JSON.stringify(b.jdm)}]`).first():b.property?f.locator(`[data-property-action=${JSON.stringify(b.property)}]`).first():b.bus?f.locator(`[data-audio-bus=${JSON.stringify(b.bus)}]`):b.toggle?f.locator(`[data-audio-toggle=${JSON.stringify(b.toggle)}]`):f.locator('#phoneOverlay').getByRole('button',{name:String(b.label).trim(),exact:true}).first();
   if(!await loc.count())throw Error('Unaddressed enabled phone control: '+JSON.stringify(b));await tap(key,loc);const next=await f.evaluate(()=>RAPhone.isOpen()?RAPhone.page():null);if(next&&next!==key&&!seen.has(next))queue.push([...path,b.action].filter(Boolean));
  }
 }
 // All Armory owned/mod states are reachable from purchases. Exercise their real controls in an isolated rich fixture.
 await restore();await f.evaluate(()=>{for(const g of RAIronCatalog.list().filter(g=>!g.dev))RAIronAndGrace.grant(g.id,{free:true});for(const m of RAIronCatalog.mods())RAFrag.patch('F02',`modsOwned.${m.id}`,true);window.__tapOwned=structuredClone(RAState.get());});
 const armorySubs=['','bench',...await f.evaluate(()=>RAIronCatalog.list().filter(g=>!g.dev).map(g=>'gun:'+g.id))];
 for(const sub of armorySubs){await restore();await f.evaluate(({sub})=>{RAState.write(localStorage,__tapOwned,false);RAState.load();RAPhone.openApp('armory',sub);},{sub});await page.waitForTimeout(260);const buttons=await inventory('#phoneOverlay [data-phone-action]');for(const b of buttons){await restore();await f.evaluate(sub=>{RAState.write(localStorage,__tapOwned,false);RAState.load();RAPhone.openApp('armory',sub);},sub);await page.waitForTimeout(260);await tap('owned Armory '+sub,f.locator(`[data-phone-action=${JSON.stringify(b.action)}]`).first());}}
 // Attached cosmetic controls expose REMOVE and ENGRAVE states.
 await restore();await f.evaluate(()=>{RAState.write(localStorage,__tapOwned,false);RAState.load();RAIronAndGrace.attachMod('lil_oga','gold_plating');RAIronAndGrace.attachMod('lil_oga','custom_engraving');window.__tapAttached=structuredClone(RAState.get());RAPhone.openApp('armory','gun:lil_oga');});await page.waitForTimeout(260);for(const b of await inventory('#phoneOverlay [data-phone-action]')){await restore();await f.evaluate(()=>{RAState.write(localStorage,__tapAttached,false);RAState.load();RAPhone.openApp('armory','gun:lil_oga');});await page.waitForTimeout(260);await tap('attached Armory',f.locator(`[data-phone-action=${JSON.stringify(b.action)}]`).first());}
 }
 // Shell, castle overlay, sleep confirmation, Combat 2.0 menus and minigame host controls.
 await restore();for(const b of await inventory('#screen button:not(#devPanel button)')){await restore();const loc=f.getByRole('button',{name:String(b.label).trim(),exact:true}).first();if(await loc.count())await tap('bedroom shell',loc);}
 await restore();await f.evaluate(()=>{for(const r of RACastle.ROOMS)RALife.addRoom({id:r.id});RACastle.open();});for(const action of await f.locator('[data-castle]').evaluateAll(es=>es.map(e=>e.dataset.castle))){await restore();await f.evaluate(()=>{for(const r of RACastle.ROOMS)RALife.addRoom({id:r.id});RACastle.open();});await tap('castle overlay',f.locator(`[data-castle="${action}"]`));}
 for(const menu of ['main','fight','item','hoes']){
  async function combat(){await restore();await f.evaluate(()=>{for(const id of Object.keys(RACombatData.ITEMS))RALife.addItem(id,1);window.__tapFight=RACombat2.run('bonesworth',{noPenalty:true});});await f.waitForSelector('.c2-scene');if(menu!=='main')await f.locator(`[data-c2="${menu}"]`).click({force:true});}
  await combat();const actions=await inventory('.c2-menu button');for(const b of actions){await combat();await tap('combat '+menu,f.locator(`[data-c2="${b.c2}"]`));await f.evaluate(()=>RAMinigames.quitActive());}
 }
 for(const id of await f.evaluate(()=>RAMinigames.list().map(g=>g.id))){await restore();await f.evaluate(id=>{window.__tapMini=RAMinigames.launch(id,{gunId:'mac_and_cheese'});},id);await page.waitForTimeout(60);const controls=await inventory('.ra-minigame button,.ra-minigame canvas');for(const b of controls){await restore();await f.evaluate(id=>{window.__tapMini=RAMinigames.launch(id,{gunId:'mac_and_cheese'});},id);const loc=f.locator('.ra-minigame button,.ra-minigame canvas').nth(b.i);await tap('minigame '+id,loc);}}
 const result={width:390,screens:[...screens],tapped:rows.length,withSound:rows.filter(r=>r.sound).length,failures:rows.filter(r=>!r.sound),rows,errors,scope:'Review controls, main bedroom/castle shell, phone navigation closure, purchased Armory states, combat menus, each registered minigame interactive element. Enabled controls only; sound settings reset before each tap.'};
 fs.writeFileSync('docs/evidence/build2/tap-census.json',JSON.stringify(result,null,2)+'\n');console.log('CENSUS',JSON.stringify({tapped:result.tapped,withSound:result.withSound,failures:result.failures,errors}));process.exitCode=result.failures.length||errors.length?1:0;
}finally{await browser.close();server.close();}
