import assert from 'node:assert/strict';import path from 'node:path';import{mkdir,writeFile,readFile}from'node:fs/promises';import{createHash}from'node:crypto';import{pathToFileURL}from'node:url';
const privateRoot=path.resolve(process.env.RA_COMBAT_PRIVATE_ROOT||'../combat-private');const {browserFor}=await import(pathToFileURL(path.join(privateRoot,'tools/tests/_browser.mjs')).href);
const out=path.resolve(process.env.COMBAT_EVIDENCE||'../evidence/candidate-final');await mkdir(out,{recursive:true});const cp=JSON.parse(await readFile(process.env.COMBAT_CHECKPOINT||'C:/Users/Ube/Documents/Codex/2026-10-07/task-13/evidence/earned-checkpoints/99e16d1-completed-ending-reload.json','utf8'));const rows=[];
const boot=async p=>{await p.evaluate(s=>{RAState.write(localStorage,s,false);RAState.load();},cp.save);await p.reload();await p.click('#startButton');await p.waitForFunction(()=>RAScenes.current()==='bedroom');};
for(const[width,height]of[[360,800],[390,844],[430,932],[1280,900]]){const b=await browserFor(process.env.COMBAT_DIST||'../candidate-combat',{hasTouch:true}),p=b.page;await p.setViewportSize({width,height});try{await boot(p);
 await p.evaluate(()=>{window.__contacts=[];window.__frames=[];for(const name of ['attack','feedbackAttack']){const original=RAEnemyFX[name];RAEnemyFX[name]=async spec=>{const contact=spec.onContact;return original({...spec,onContact:()=>{window.__contacts.push({enemy:spec.enemyId,move:spec.moveId,hpBefore:document.querySelector('.c2-hp-rich strong')?.textContent||document.querySelector('#richHPText')?.textContent});contact?.();}});};}
 const seen=new WeakMap();new MutationObserver(()=>{for(const c of document.querySelectorAll('canvas[data-choreography="feedback"]')){const f=c.dataset.frame;if(seen.get(c)===f)continue;seen.set(c,f);__frames.push({id:c.dataset.presentation,frame:Number(f),png:c.toDataURL(),pose:document.querySelector('.c2-enemy')?.getAttribute('src')||document.querySelector('#productionCEO')?.style.backgroundImage});}}).observe(document.querySelector('#screen'),{subtree:true,childList:true,attributes:true,attributeFilter:['data-frame']});
 RACombat2.run('gbenga',{env:'gbenga_rentals',noPenalty:true});RACombat2.active().state.rng=()=>.5;});
 const before=await p.evaluate(()=>({hp:RACombat2.active().state.rich.hp,enemy:RACombat2.active().state.enemy.hp,pp:RACombat2.active().state.rich.pp.blood}));await p.locator('[data-c2="fight"]').tap();await p.locator('[data-c2="move:blood"]').tap();await p.waitForFunction(()=>RACombat2.active()&&!RACombat2.active().busy(),null,{timeout:30000});
 const first=await p.evaluate(()=>{const s=RACombat2.active().state;return{hp:s.rich.hp,enemy:s.enemy.hp,pp:s.rich.pp.blood,equipped:s.f07.dracoEquipped,phoneUsed:s.f07.phoneUsed,next:RACombat2Rules.intent(s),contacts:__contacts.slice()};});assert.equal(first.hp,before.hp-24);assert.equal(first.pp,before.pp-1);assert.equal(first.equipped,true);assert.equal(first.phoneUsed,true);assert.equal(first.next,'draco');assert.equal(first.contacts.filter(x=>x.move==='phone').length,1);
 await p.locator('[data-c2="fight"]').tap();await p.locator('[data-c2="move:bite"]').tap();await p.waitForFunction(()=>RACombat2.active()&&!RACombat2.active().busy(),null,{timeout:30000});const second=await p.evaluate(()=>{const s=RACombat2.active().state;return{hp:s.rich.hp,pp:s.rich.pp.bite,next:RACombat2Rules.intent(s),contacts:__contacts.slice(),log:s.log,f07:s.f07};});assert.equal(second.hp,Math.min(before.hp,first.hp+18)-40);assert.equal(second.pp,7);assert.equal(second.next,'voice');assert.equal(second.contacts.filter(x=>x.move==='draco').length,1);
 // Frozen visual contact samples are separate from the native turn evidence above.
 for(const[move,frame]of[['phone',4],['phone',6],['draco',7]]){await p.evaluate(({move,frame})=>{const root=document.querySelector('.c2-scene');window.__frozen=RAEnemyFX.attack({root,enemyId:'gbenga',moveId:move,attacker:root.querySelector('.c2-enemy'),target:root.querySelector('.c2-rich'),freeze:frame});},{move,frame});await p.waitForTimeout(110);await p.screenshot({path:path.join(out,`${width}-gbenga-${move}-f${frame}.png`)});await p.evaluate(()=>__frozen);}
 const clean=await p.evaluate(()=>({layers:document.querySelectorAll('[data-choreography="feedback"]').length,targetStyle:document.querySelector('.c2-rich').getAttribute('style')}));assert.equal(clean.layers,0);
 // Real JDM menu action and enemy-turn adapter; select each existing weighted option explicitly for coverage.
 await p.evaluate(()=>{RACombat2.active().abort();RAScenes.go('jdmCombat');const original=RACombatFoundation.selectEnemyMove;let turn=0;RACombatFoundation.selectEnemyMove=(s,r)=>s.encounterId==='jdm'?RACombatDefinitions.moves[turn++%2?'importer_parts':'importer_shove']:original(s,r);});
 const jdm=[];for(const move of ['importer_shove','importer_parts']){const hp=await p.locator('#richHPText').innerText();await p.locator('[data-move="blood"]').tap();await p.waitForFunction(()=>document.querySelector('#battleUI').getAttribute('aria-busy')==='false',null,{timeout:30000});const after=await p.locator('#richHPText').innerText();assert.equal(parseInt(after),parseInt(hp)-16);jdm.push({move,before:hp,after});}
 for(const move of ['importer_shove','importer_parts']){await p.evaluate(move=>{window.__frozen=RAEnemyFX.feedbackAttack({root:document.querySelector('#screen'),enemyId:'legacy_importer',moveId:move,attacker:document.querySelector('#productionCEO'),target:document.querySelector('#geminiRich'),freeze:6});},move);await p.waitForTimeout(110);await p.screenshot({path:path.join(out,`${width}-jdm-${move}-contact.png`)});await p.evaluate(()=>__frozen);}
 const native=await p.evaluate(()=>({contacts:__contacts,frames:__frames}));const frames=native.frames.filter(f=>f.png.length>150);for(const[id,expected]of[['enemy:gbenga:phone',12],['enemy:gbenga:draco',16],['enemy:legacy_importer:importer_shove',12],['enemy:legacy_importer:importer_parts',12]]){const count=new Set(frames.filter(f=>f.id===id).map(f=>f.frame)).size;assert.equal(count,expected,id+' frame coverage');}
 if(width===390){for(const f of frames){const name=f.id.replaceAll(':','-')+'-f'+f.frame+'.png';await writeFile(path.join(out,name),Buffer.from(f.png.split(',')[1],'base64'));}}
 // Duplicate/replacement owner cleanup, cancel before contact and after contact, reduced motion.
 const lifecycle=await p.evaluate(async()=>{const root=document.querySelector('#screen'),a=document.querySelector('#productionCEO'),t=document.querySelector('#geminiRich'),src=a.getAttribute('style'),ts=t.getAttribute('style'),pause=ms=>new Promise(r=>setTimeout(r,ms));const result=[];
 for(const delay of [50,540]){let contacts=0;const q=RAEnemyFX.feedbackAttack({root,enemyId:'legacy_importer',moveId:'importer_shove',attacker:a,target:t,onContact:()=>contacts++});if(delay===50)await pause(delay);else{for(let i=0;i<150&&contacts===0;i++)await pause(16);if(contacts!==1)throw Error('contact not observed before post-contact cancellation');}RAEnemyFX.cancel(root);await q;result.push({delay,contacts,restored:a.getAttribute('style')===src&&t.getAttribute('style')===ts,layers:root.querySelectorAll('[data-choreography="feedback"]').length});}
 let c1=0,c2=0;const q1=RAEnemyFX.feedbackAttack({root,enemyId:'legacy_importer',moveId:'importer_shove',attacker:a,target:t,onContact:()=>c1++});await pause(30);const q2=RAEnemyFX.feedbackAttack({root,enemyId:'legacy_importer',moveId:'importer_parts',attacker:a,target:t,onContact:()=>c2++});await Promise.all([q1,q2]);return{result,replacement:{c1,c2,restored:a.getAttribute('style')===src&&t.getAttribute('style')===ts,layers:root.querySelectorAll('[data-choreography="feedback"]').length}};});assert.deepEqual(lifecycle.result.map(x=>x.contacts),[0,1]);assert.ok(lifecycle.result.every(x=>x.restored&&x.layers===0));assert.deepEqual(lifecycle.replacement,{c1:0,c2:1,restored:true,layers:0});
 await p.emulateMedia({reducedMotion:'reduce'});const reduced=await p.evaluate(async()=>{const root=document.querySelector('#screen');let contact=0;const elapsed=await RAEnemyFX.feedbackAttack({root,enemyId:'legacy_importer',moveId:'importer_parts',attacker:document.querySelector('#productionCEO'),target:document.querySelector('#geminiRich'),onContact:()=>contact++});return{elapsed,contact,layers:root.querySelectorAll('[data-choreography="feedback"]').length};});assert.deepEqual(reduced,{elapsed:220,contact:1,layers:0});
 await p.emulateMedia({reducedMotion:'no-preference'});
 // Interrupt an actual legacy enemy turn before its observed contact frame, then reenter.
 await p.evaluate(()=>{RAScenes.go('bedroom');RAScenes.go('jdmCombat');__contacts=[];});await p.locator('[data-move="blood"]').tap();await p.waitForSelector('[data-choreography="feedback"]');await p.evaluate(()=>RAScenes.go('bedroom'));await p.waitForTimeout(1200);const interrupted=await p.evaluate(()=>({scene:RAScenes.current(),contacts:__contacts.length,layers:document.querySelectorAll('[data-choreography="feedback"]').length}));assert.deepEqual(interrupted,{scene:'bedroom',contacts:0,layers:0});await p.evaluate(()=>RAScenes.go('jdmCombat'));assert.equal(await p.locator('#richHPText').innerText(),'100/100');
 const durable=await p.evaluate(()=>({money:RALife.money(),cars:RALife.ownedCars(),day:RALife.today().day}));await p.reload();await p.click('#startButton');await p.waitForFunction(()=>RAScenes.current()==='bedroom');assert.deepEqual(await p.evaluate(()=>({money:RALife.money(),cars:RALife.ownedCars(),day:RALife.today().day})),durable);assert.equal(await p.locator('[data-choreography="feedback"]').count(),0);assert.deepEqual(b.errors,[]);
 rows.push({width,height,before,first,second,jdm,lifecycle,reduced,interrupted,frameCounts:Object.fromEntries([...new Set(frames.map(f=>f.id))].map(id=>[id,new Set(frames.filter(f=>f.id===id).map(f=>f.frame)).size])),uniqueDrawnFrames:new Set(frames.map(f=>createHash('sha256').update(f.png).digest('hex'))).size,errors:b.errors});console.log('PASS native/scoped lifecycle width',width);
 }catch(e){await p.screenshot({path:path.join(out,`${width}-failure.png`)});await writeFile(path.join(out,'failure.json'),JSON.stringify({error:e.stack,errors:b.errors,state:await p.evaluate(()=>({scene:RAScenes.current(),active:RACombat2.active()?.state,text:document.querySelector('#screen')?.innerText})),rows},null,2));throw e;}finally{await b.close();}}
await writeFile(path.join(out,'results.json'),JSON.stringify({scope:'Earned QA checkpoint copied into fresh headless Chromium; native FIGHT/BLOOD/BITE and JDM menu taps. Deterministic player RNG and each weighted JDM option selected only to assure coverage. Contact visual screenshots separately frozen. Scoped cancel/replacement/reduced/reload; no full campaign claim.',rows},null,2));
