#!/usr/bin/env node
// Lists every PLACEHOLDER surface in the build (environments, characters, audio) → docs/btf/ART_INPUTS.md.
import path from 'node:path';import {writeFile} from 'node:fs/promises';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const {loadBtf}=await import(pathToFileURL(path.join(root,'tools','btf-test.mjs')).href);
const ctx=await loadBtf(root);
const envs=ctx.RAEnvironments.all();const people=[...ctx.RABtfPeople.list];
const used=new Set();for(const a of ctx.RAAdventures.all())for(const n of Object.values(a.nodes))if(typeof n.env==='string')used.add(n.env);
const lines=['# REQUIRED ART & AUDIO INPUTS (Rough Complete placeholders)','','Generated by `node tools/art-inputs.mjs`. Everything listed renders today as an honest placeholder (RAPixel shapes). Approved/frozen art is reused where it exists and is never modified. Primary characters display at the central 1.85× scale (js/engine/display.js); compose new 270×480 environments with a deep floor band (contact line ≈ y 372) for 2–3 actors plus a bottom dialogue box.','',
 '## Environments (270×480 masters)','','| id | location | referenced by static nodes |','|---|---|---|',...envs.filter(e=>e.placeholder).map(e=>`| ${e.id} | ${e.name} | ${used.has(e.id)?'yes':'dynamic/optional'} |`),'',
 '## Characters without approved sprites (80×96, contact 40,88)','','| id | name | role |','|---|---|---|',...people.filter(p=>!p.sprite&&p.look).map(p=>`| ${p.id} | ${p.name} | ${p.role||p.species||''} |`),'',
 '## Rich contextual states (VOL 2 §1)','','Driving HUD face, fishing arm\'s-length, ramen apron, laptop, on stage, riding Mazda, Portobello transformation, hungover — all currently use rich_standing_right.png or placeholders.','',
 '## Creatures / props / vehicles','','Blueberry Mazda (egg → majestic, human form), sphynx cat, pier catches, Dragon Maggi Cube, Agege bread, guns (case + combat), top-down TOUGE cars (Supra, S15 ±kit, S2000, R34, Urus, Aventador, Ferrari) and world sprites for new cars, bedroom company overlays and bedroom props.','',
 '## Audio loops','','Only BLOODBATH (assets/bloodbath_mix3.wav) ships. Needed: PLAYMAKERS, OCTOPUS BRAIN, MONTANA, SHOPPING ADDICT loops (28–55 s) → set `file` in js/systems/radio.js.'];
await writeFile(path.join(root,'docs/btf/ART_INPUTS.md'),lines.join('\n')+'\n');console.log(`placeholder envs ${envs.filter(e=>e.placeholder).length}, characters ${people.filter(p=>!p.sprite&&p.look).length}`);
