#!/usr/bin/env node
// Generates js/data/presentation_assets.js — per-asset presentation metadata for the Presentation Director:
// dimensions, sha256, visible (alpha) bounds, contact anchor and face box. Frozen PNGs are only read.
// Usage: node tools/presentation-assets.mjs            (write)
//        import {expectedAssets} for the release gate   (verify up to date)
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {decodePng,alphaBox} from './presentation/png.mjs';
import {buildRegistry} from './art-registry.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const target=path.join(root,'js/data/presentation_assets.js');

// Derived face box when none is authored: upper part of the visible body, central columns.
function derivedFace([x,y,w,h]){return [Math.round(x+w*.15),Math.round(y+h*.16),Math.max(1,Math.round(w*.7)),Math.max(1,Math.round(h*.3))];}

export async function buildAssets(){
 const annotations=JSON.parse(await readFile(path.join(root,'tools/presentation/annotations.json'),'utf8'));
 const register=JSON.parse(await readFile(path.join(root,'art_department/ASSET_REGISTER.json'),'utf8')).assets;
 const status=Object.fromEntries(register.map(item=>[item.path,{status:item.status,sha256:item.sha256}]));
 // Every frozen ART SHIP 004–007 environment and actor in the generated Art Registry gets metadata automatically;
 // annotations.json only adds authored detail (face boxes). Contacts come from the Ship manifests.
 const registry=await buildRegistry(),notes={...annotations.assets};
 for(const e of Object.values(registry.environments))for(const file of [e.asset,...Object.values(e.layers||{})])if(file)notes[file]={environment:true,...notes[file]};
 for(const c of Object.values(registry.characters))for(const file of Object.values(c.states))notes[file]={...(c.contact?{anchor:c.contact}:{}),...notes[file]};
 for(const c of Object.values(registry.creatures))notes[c.anchor]={...(c.contact?{anchor:c.contact}:{groundedAnchor:true}),...notes[c.anchor]};
 const assets={};
 for(const [file,note] of Object.entries(notes).sort(([a],[b])=>a.localeCompare(b))){
  const bytes=await readFile(path.join(root,file)),png=decodePng(bytes),sha256=createHash('sha256').update(bytes).digest('hex');
  const registered=status[file];
  if(registered&&registered.sha256!==sha256)throw new Error(`${file}: bytes differ from ASSET_REGISTER.json (frozen authority)`);
  const entry={width:png.width,height:png.height,sha256,authority:registered?.status||'UNREGISTERED'};
  if(note.environment)entry.environment=true;
  else if(note.frames){
   // Horizontal sprite sheet: one metadata entry per frame, keyed `<path>#<index>`; the sheet entry lists them.
   const fw=note.frames.width,count=Math.round(png.width/fw);entry.sheet={frameWidth:fw,frames:count};assets[file]=entry;
   for(let i=0;i<count;i++){const frame={width:fw,height:png.height,data:Buffer.alloc(fw*png.height*4)};for(let y=0;y<png.height;y++)png.data.copy(frame.data,y*fw*4,(y*png.width+i*fw)*4,(y*png.width+(i+1)*fw)*4);
    const visible=alphaBox(frame),face=note.frames.faces?.[i];assets[`${file}#${i}`]={width:fw,height:png.height,sha256,authority:entry.authority,visible,anchor:note.anchor||annotations.defaultAnchor,face:face||derivedFace(visible),faceSource:face?'authored':'derived'}}
   continue;
  }
  else{
   const visible=alphaBox(png);
   entry.visible=visible;
   // Creatures without an authored contact stand on the bottom-centre of their visible pixels.
   entry.anchor=note.anchor||(note.groundedAnchor?[visible[0]+Math.floor(visible[2]/2),visible[1]+visible[3]]:annotations.defaultAnchor);
   entry.face=note.face||derivedFace(visible);
   entry.faceSource=note.face?'authored':'derived';
   if(note.noFace)entry.noFace=true;
  }
  assets[file]=entry;
 }
 return assets;
}

export async function expectedAssets(){
 const assets=await buildAssets();
 return `(function(){\n // GENERATED by tools/presentation-assets.mjs from tools/presentation/annotations.json — do not edit by hand.\n // Source pixels: visible = alpha bounds [x,y,w,h]; anchor = contact point; face = face box. Frozen PNGs are never modified.\n window.RAPresentationAssets={\n${Object.entries(assets).map(([file,entry])=>`  ${JSON.stringify(file)}:${JSON.stringify(entry)}`).join(',\n')}\n };\n})();\n`;
}

if(process.argv[1]===fileURLToPath(import.meta.url)){await writeFile(target,await expectedAssets());console.log('js/data/presentation_assets.js written');}
