#!/usr/bin/env node
// Generates js/data/presentation_assets.js — per-asset presentation metadata for the Presentation Director:
// dimensions, sha256, visible (alpha) bounds, contact anchor and face box. Frozen PNGs are only read.
// Usage: node tools/presentation-assets.mjs            (write)
//        import {expectedAssets} for the release gate   (verify up to date)
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {decodePng,alphaBox} from './presentation/png.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const target=path.join(root,'js/data/presentation_assets.js');

// Derived face box when none is authored: upper part of the visible body, central columns.
function derivedFace([x,y,w,h]){return [Math.round(x+w*.15),Math.round(y+h*.16),Math.max(1,Math.round(w*.7)),Math.max(1,Math.round(h*.3))];}

export async function buildAssets(){
 const annotations=JSON.parse(await readFile(path.join(root,'tools/presentation/annotations.json'),'utf8'));
 const register=JSON.parse(await readFile(path.join(root,'art_department/ASSET_REGISTER.json'),'utf8')).assets;
 const status=Object.fromEntries(register.map(item=>[item.path,{status:item.status,sha256:item.sha256}]));
 const assets={};
 for(const [file,note] of Object.entries(annotations.assets).sort(([a],[b])=>a.localeCompare(b))){
  const bytes=await readFile(path.join(root,file)),png=decodePng(bytes),sha256=createHash('sha256').update(bytes).digest('hex');
  const registered=status[file];
  if(registered&&registered.sha256!==sha256)throw new Error(`${file}: bytes differ from ASSET_REGISTER.json (frozen authority)`);
  const entry={width:png.width,height:png.height,sha256,authority:registered?.status||'UNREGISTERED'};
  if(note.environment)entry.environment=true;
  else{
   const visible=alphaBox(png);
   entry.visible=visible;
   entry.anchor=note.anchor||annotations.defaultAnchor;
   entry.face=note.face||derivedFace(visible);
   entry.faceSource=note.face?'authored':'derived';
  }
  assets[file]=entry;
 }
 return assets;
}

export async function expectedAssets(){
 const assets=await buildAssets();
 return `(function(){\n // GENERATED by tools/presentation-assets.mjs from tools/presentation/annotations.json — do not edit by hand.\n // Source pixels: visible = alpha bounds [x,y,w,h]; anchor = contact point; face = face box. Frozen PNGs are never modified.\n window.RAPresentationAssets={\n${Object.entries(assets).map(([file,entry])=>`  ${JSON.stringify(file)}:${JSON.stringify(entry)}`).join(',\n')}\n };\n})();\n`;
}

if(process.argv[1]===fileURLToPath(import.meta.url)){await writeFile(target,await expectedAssets());console.log('js/data/presentation_assets.js written');}
