// RC3 · BUILD A — generates docs/rc3/CUT_LIST.md (titles only, kept vs cut) from the live data, for Ube to veto.
//   node tools/rc3/cut-list.mjs
import path from 'node:path';
import fs from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');
const url=f=>pathToFileURL(path.join(root,f)).href;
const {careerBoot}=await import(url('tools/tests/f13/_career.mjs'));
const {run}=await import(url('tools/tests/if1/_lib.mjs'));
const {c}=await careerBoot(root,{seed:1,persona:'explorer'});await run(root,c,['js/systems/rc3_cut.js']);
const K=c.RARC3Cut,A=c.RAAdventures;
const all=A.all(),by={spine:[],functional:[],stripper:[],optional:[],cut:[]};
for(const d of all)by[K.classify(d.id)].push(d);
const t=d=>d.title;const list=(xs,f=t)=>xs.map(x=>`- ${f(x)}`).join('\n');
// ---- characters: kept = anyone on screen in a kept adventure, an enemy, a dancer, the crew; cut = every other named person
const people=c.RABtfPeople.byId,idsIn=def=>{const out=new Set();for(const n of Object.values(def.nodes||{})){for(const v of Object.values(typeof n.actors==='object'&&n.actors||{}))out.add(typeof v==='string'?v:v?.id);
 for(const l of Array.isArray(n.lines)?n.lines:[])if(Array.isArray(l)&&typeof l[0]==='string')out.add(l[0].toLowerCase());if(n.fight?.enemy)out.add(n.fight.enemy);}
 if(def.testVars?.person)out.add(def.testVars.person);return out;};
const keptDefs=[...by.spine,...by.functional,...by.stripper,...by.optional];
const keep=new Set(['rich']);for(const d of keptDefs)for(const id of idsIn(d))if(id)keep.add(id);
for(const e of Object.values(c.RACombatData.ENEMIES))if(e.person)keep.add(e.person);
for(const id of ['roxy','rosalyn','emerald','granny_bing','spirit_of_uncle_bunmi','gbenga','carlos','senator','mister_december','velvet'])keep.add(id);
const named=Object.values(people).filter(p=>p&&p.name&&!p.f15&&!/^(soul|extra)/.test(p.id));
const KEEP_NAMES=['OGUN','DEACON BRASS','SHANNON','MR. OKADA','MOM','DAD','SISTER','BIG BRO','LIL BRO','MISTER DECEMBER'];   // the rave host, the armory, the property agent, the day job, the family text thread
const isKept=p=>keep.has(p.id)||KEEP_NAMES.includes(String(p.name).toUpperCase());
const seenNames=new Set(),uniq=ps=>ps.filter(p=>!seenNames.has(p.name)&&seenNames.add(p.name));
const keptPeople=uniq(named.filter(isKept)),cutPeople=uniq(named.filter(p=>!isKept(p)));
const apps=K.APPS.map(a=>a.label);
const cutApps=['InstaHoe','OnlyVamps','RICHBOIMPORTS','JDMIMPORTS (now a page inside Bank → CARS)','RealMoneyRealEstate (now Bank → PROPERTY)','Contacts','Receipts','Hatch (dragon care)','Touge','Bars','Moves','Rainmaker (the old tile)','The Trap (F05)','VampGram (now the FEED row inside Texts)'];
const mg=fs.readdirSync(path.join(root,'js/minigames')).filter(f=>f.endsWith('.js')&&f!=='index.js').map(f=>f.replace('.js',''));
const cat=c.RAIronCatalog;const guns=cat.list().filter(g=>!g.dev);
const md=`# RC3 · THE CUT — kept vs cut (titles only, for Ube to veto)

Generated by \`node tools/rc3/cut-list.mjs\` from the live data (\`js/data/rc3_cut.js\`). **Cut = removed from play: unreachable and not shown. Code and assets stay in the repo.**
Pillars: funny jokes · a clear story · cool sexy strippers · awesome fights · adventures only if the player chooses.

## Counts
| | kept | cut |
|---|---|---|
| Phone apps | ${apps.length} | ${cutApps.length} |
| Adventures (${all.length} defined) | ${by.spine.length+by.functional.length+by.stripper.length+by.optional.length} (spine ${by.spine.length} · system ${by.functional.length} · dancer dates ${by.stripper.length} · Maps ${by.optional.length}) | ${by.cut.length} |
| Minigames | ${K.MINIGAMES_KEEP.length} (4 standalone + 2 story-only beats) | ${mg.length-K.MINIGAMES_KEEP.filter(x=>mg.includes(x)).length} |
| Guns | ${K.GUNS_KEEP.length} | ${guns.length-K.GUNS_KEEP.length} + all ${Object.keys(cat.MODS||{}).length} mods |
| Named side characters | ${keptPeople.length} | ${cutPeople.length} |

## Phone: 8 apps
${list(apps,x=>x)}

Cut apps (hidden; the essential job folded into one of the eight):
${list(cutApps,x=>x)}

## Adventures — kept
### Story spine (never random; the story delivers them)
${list(by.spine)}
Plus the ladder's later beats (THE TURF WAR, THE TRIBUTE, VICE PRESIDENT, THE CALL) and OGUN'S RAVE (a scene, not an adventure).
### Systems the phone runs (not random adventures)
${list(by.functional)}
### The dancers' dates (reached inside the strip club)
${list(by.stripper,d=>`${d.title} (${d.id})`)}
### Maps: the ten optional adventures (best first; the ONLY way to reach them)
${list(K.OPTIONAL,o=>`${A.get(o.id).title} · ${o.tag}`)}

## Adventures — cut (${by.cut.length})
${list(by.cut)}

## Minigames
Kept standalone: slurp (ramen), dance (the rave dance), range_day, the strip club (MAKE IT RAIN).
Kept ONLY as beats inside the story (SET UP CARLOS / JUG THE PLUG, THE OWAMBE COLLECTION): touge, owambe_collection.
Cut: ${list(mg.filter(x=>!K.MINIGAMES_KEEP.includes(x)),x=>x).split('\n').join(' ')}

## Guns
Kept: ${K.GUNS_KEEP.map(id=>cat.byId(id)?.label||id).join(' · ')}
Cut: ${guns.filter(g=>!K.GUNS_KEEP.includes(g.id)).map(g=>g.label).join(' · ')}
Mods (all hidden): ${Object.values(cat.MODS||{}).map(m=>m.label).join(' · ')}

## Combat menu
Core four (BLOOD BATH · OCTOPUS BRAIN · VAMPIRE BITE · REVENGE) + the equipped gun + one learned move (swap in the ARMORY) = at most ${K.COMBAT_MENU_MAX}. HOES (companion moves) is gone from the menu.

## Party events
Kept (all tied to the story): OGUN'S RAVE (the big one) · CANOPY DUTY (the Carson owambe) · THE OWAMBE COLLECTION.
Cut: every castle party, the Duchess's soirée, Halloween, the rooftop and the neighbour's castle, Ogun's second rave.

## Side characters
Kept (${keptPeople.length}): ${keptPeople.map(p=>p.name).join(' · ')}
Cut (${cutPeople.length}): ${cutPeople.map(p=>p.name).join(' · ')}

## Other cuts
- THE TRAP (F05): flag OFF. Non-stripper dates: no InstaHoe, no DATE adventure, no romance arcs. Castle rooms: not purchasable-and-visitable any more (the castle button opens the throne room only).
- Random wants, "WHAT WE ON", the MAKE MONEY / MEET PEOPLE / GO SOMEWHERE lanes, the morning mail stack, wake-time random adventures, every phone INCOMING except Ogun's invite.
- Ladder exits that ended the story early: NAH (JUG THE PLUG), BUY A BOBA AND LEAVE, PAY $20,000 · END.
`;
fs.mkdirSync(path.join(root,'docs/rc3'),{recursive:true});fs.writeFileSync(path.join(root,'docs/rc3/CUT_LIST.md'),md);
console.log(JSON.stringify({adventures:{total:all.length,spine:by.spine.length,functional:by.functional.length,stripper:by.stripper.length,optional:by.optional.length,cut:by.cut.length},people:{kept:keptPeople.length,cut:cutPeople.length},minigamesCut:mg.length-K.MINIGAMES_KEEP.filter(x=>mg.includes(x)).length,gunsCut:guns.length-K.GUNS_KEEP.length}));
